// Code generated by protoc-gen-go-orm. DO NOT EDIT.
// versions:
//  protoc-gen-go-orm v0.1.0
//  protoc           v7.34.1
// source: players.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mg_players.proto

package mongo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Player
// KV 存储记录（PAYLOAD：键字段 + data）
type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       int64                  `protobuf:"varint,27,opt,name=version,proto3" json:"version,omitempty"`
	Data          []byte                 `protobuf:"bytes,999,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_mg_players_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_mg_players_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_mg_players_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Player) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_mg_players_proto protoreflect.FileDescriptor

const file_mg_players_proto_rawDesc = "" +
	"\n" +
	"\x10mg_players.proto\x12\x05mongo\"[\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x1b \x01(\x03R\aversion\x12\x13\n" +
	"\x04data\x18\xe7\a \x01(\fR\x04dataBBZ@github.com/wxdqing/protoc-gen-go-orm/examples/src/internal/mongob\x06proto3"

var (
	file_mg_players_proto_rawDescOnce sync.Once
	file_mg_players_proto_rawDescData []byte
)

func file_mg_players_proto_rawDescGZIP() []byte {
	file_mg_players_proto_rawDescOnce.Do(func() {
		file_mg_players_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mg_players_proto_rawDesc), len(file_mg_players_proto_rawDesc)))
	})
	return file_mg_players_proto_rawDescData
}

var file_mg_players_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mg_players_proto_goTypes = []any{
	(*Player)(nil), // 0: mongo.Player
}
var file_mg_players_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mg_players_proto_init() }
func file_mg_players_proto_init() {
	if File_mg_players_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mg_players_proto_rawDesc), len(file_mg_players_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mg_players_proto_goTypes,
		DependencyIndexes: file_mg_players_proto_depIdxs,
		MessageInfos:      file_mg_players_proto_msgTypes,
	}.Build()
	File_mg_players_proto = out.File
	file_mg_players_proto_goTypes = nil
	file_mg_players_proto_depIdxs = nil
}
