// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: orm.option.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TableStoreMode int32

const (
	TableStoreMode_TABLE_STORE_MODE_PAYLOAD TableStoreMode = 0 // pk/index/version + data payload
	TableStoreMode_TABLE_STORE_MODE_FIELDS  TableStoreMode = 1 // field expansion: simple columns, complex JSON
)

// Enum value maps for TableStoreMode.
var (
	TableStoreMode_name = map[int32]string{
		0: "TABLE_STORE_MODE_PAYLOAD",
		1: "TABLE_STORE_MODE_FIELDS",
	}
	TableStoreMode_value = map[string]int32{
		"TABLE_STORE_MODE_PAYLOAD": 0,
		"TABLE_STORE_MODE_FIELDS":  1,
	}
)

func (x TableStoreMode) Enum() *TableStoreMode {
	p := new(TableStoreMode)
	*p = x
	return p
}

func (x TableStoreMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableStoreMode) Descriptor() protoreflect.EnumDescriptor {
	return file_orm_option_proto_enumTypes[0].Descriptor()
}

func (TableStoreMode) Type() protoreflect.EnumType {
	return &file_orm_option_proto_enumTypes[0]
}

func (x TableStoreMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TableStoreMode.Descriptor instead.
func (TableStoreMode) EnumDescriptor() ([]byte, []int) {
	return file_orm_option_proto_rawDescGZIP(), []int{0}
}

var file_orm_option_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         847900,
		Name:          "orm.tcaplus_primary_key",
		Tag:           "bytes,847900,opt,name=tcaplus_primary_key",
		Filename:      "orm.option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         847901,
		Name:          "orm.tcaplus_index",
		Tag:           "bytes,847901,rep,name=tcaplus_index",
		Filename:      "orm.option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         847902,
		Name:          "orm.tcaplus_field_cipher_suite",
		Tag:           "bytes,847902,opt,name=tcaplus_field_cipher_suite",
		Filename:      "orm.option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         847903,
		Name:          "orm.tcaplus_record_cipher_suite",
		Tag:           "bytes,847903,opt,name=tcaplus_record_cipher_suite",
		Filename:      "orm.option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         847904,
		Name:          "orm.tcaplus_cipher_md5",
		Tag:           "bytes,847904,opt,name=tcaplus_cipher_md5",
		Filename:      "orm.option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         847905,
		Name:          "orm.tcaplus_sharding_key",
		Tag:           "bytes,847905,opt,name=tcaplus_sharding_key",
		Filename:      "orm.option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         847906,
		Name:          "orm.tcaplus_customattr",
		Tag:           "bytes,847906,opt,name=tcaplus_customattr",
		Filename:      "orm.option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         847900,
		Name:          "orm.tcaplus_size",
		Tag:           "varint,847900,opt,name=tcaplus_size",
		Filename:      "orm.option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         847901,
		Name:          "orm.tcaplus_desc",
		Tag:           "bytes,847901,opt,name=tcaplus_desc",
		Filename:      "orm.option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         847902,
		Name:          "orm.tcaplus_crypto",
		Tag:           "varint,847902,opt,name=tcaplus_crypto",
		Filename:      "orm.option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         60030,
		Name:          "orm.table",
		Tag:           "varint,60030,opt,name=table",
		Filename:      "orm.option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         60031,
		Name:          "orm.node_type",
		Tag:           "bytes,60031,opt,name=node_type",
		Filename:      "orm.option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*TableStoreMode)(nil),
		Field:         60032,
		Name:          "orm.table_store_mode",
		Tag:           "varint,60032,opt,name=table_store_mode,enum=orm.TableStoreMode",
		Filename:      "orm.option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         847939,
		Name:          "orm.tags",
		Tag:           "bytes,847939,opt,name=tags",
		Filename:      "orm.option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         847940,
		Name:          "orm.primary_key",
		Tag:           "varint,847940,opt,name=primary_key",
		Filename:      "orm.option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         847941,
		Name:          "orm.skip_set_default",
		Tag:           "varint,847941,opt,name=skip_set_default",
		Filename:      "orm.option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         847942,
		Name:          "orm.index",
		Tag:           "varint,847942,opt,name=index",
		Filename:      "orm.option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         847943,
		Name:          "orm.sharding_key",
		Tag:           "varint,847943,opt,name=sharding_key",
		Filename:      "orm.option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         847939,
		Name:          "orm.oneof_tags",
		Tag:           "bytes,847939,opt,name=oneof_tags",
		Filename:      "orm.option.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional string tcaplus_primary_key = 847900;
	E_TcaplusPrimaryKey = &file_orm_option_proto_extTypes[0] //Tcaplus Primary Key
	// repeated string tcaplus_index = 847901;
	E_TcaplusIndex = &file_orm_option_proto_extTypes[1] //Tcaplus Index
	// optional string tcaplus_field_cipher_suite = 847902;
	E_TcaplusFieldCipherSuite = &file_orm_option_proto_extTypes[2] //Tcaplus field crypto suite name
	// optional string tcaplus_record_cipher_suite = 847903;
	E_TcaplusRecordCipherSuite = &file_orm_option_proto_extTypes[3] //Tcaplus record crypto suite name
	// optional string tcaplus_cipher_md5 = 847904;
	E_TcaplusCipherMd5 = &file_orm_option_proto_extTypes[4] //Tcaplus crypto key md5
	// optional string tcaplus_sharding_key = 847905;
	E_TcaplusShardingKey = &file_orm_option_proto_extTypes[5] //Tcaplus sharding key
	// optional string tcaplus_customattr = 847906;
	E_TcaplusCustomattr = &file_orm_option_proto_extTypes[6] //Tcaplus custom define attribute
	// optional bool table = 60030;
	E_Table = &file_orm_option_proto_extTypes[10]
	// optional string node_type = 60031;
	E_NodeType = &file_orm_option_proto_extTypes[11]
	// optional orm.TableStoreMode table_store_mode = 60032;
	E_TableStoreMode = &file_orm_option_proto_extTypes[12]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional uint32 tcaplus_size = 847900;
	E_TcaplusSize = &file_orm_option_proto_extTypes[7] // Tcaplus field size
	// optional string tcaplus_desc = 847901;
	E_TcaplusDesc = &file_orm_option_proto_extTypes[8] // Tcaplus description
	// optional bool tcaplus_crypto = 847902;
	E_TcaplusCrypto = &file_orm_option_proto_extTypes[9] // Tcaplus crypto
	// Multiple Tags can be specified.
	//
	// optional string tags = 847939;
	E_Tags = &file_orm_option_proto_extTypes[13]
	// optional bool primary_key = 847940;
	E_PrimaryKey = &file_orm_option_proto_extTypes[14] // Marks this field as a primary key
	// optional bool skip_set_default = 847941;
	E_SkipSetDefault = &file_orm_option_proto_extTypes[15] // ignore default value assignment for this field
	// optional bool index = 847942;
	E_Index = &file_orm_option_proto_extTypes[16] // Marks this field as index
	// optional bool sharding_key = 847943;
	E_ShardingKey = &file_orm_option_proto_extTypes[17] // Marks this field as tcaplus sharding key
)

// Extension fields to descriptorpb.OneofOptions.
var (
	// Multiple Tags can be specified.
	//
	// optional string oneof_tags = 847939;
	E_OneofTags = &file_orm_option_proto_extTypes[18]
)

var File_orm_option_proto protoreflect.FileDescriptor

const file_orm_option_proto_rawDesc = "" +
	"\n" +
	"\x10orm.option.proto\x12\x03orm\x1a google/protobuf/descriptor.proto*K\n" +
	"\x0eTableStoreMode\x12\x1c\n" +
	"\x18TABLE_STORE_MODE_PAYLOAD\x10\x00\x12\x1b\n" +
	"\x17TABLE_STORE_MODE_FIELDS\x10\x01:Q\n" +
	"\x13tcaplus_primary_key\x12\x1f.google.protobuf.MessageOptions\x18\x9c\xe03 \x01(\tR\x11tcaplusPrimaryKey:F\n" +
	"\rtcaplus_index\x12\x1f.google.protobuf.MessageOptions\x18\x9d\xe03 \x03(\tR\ftcaplusIndex:^\n" +
	"\x1atcaplus_field_cipher_suite\x12\x1f.google.protobuf.MessageOptions\x18\x9e\xe03 \x01(\tR\x17tcaplusFieldCipherSuite:`\n" +
	"\x1btcaplus_record_cipher_suite\x12\x1f.google.protobuf.MessageOptions\x18\x9f\xe03 \x01(\tR\x18tcaplusRecordCipherSuite:O\n" +
	"\x12tcaplus_cipher_md5\x12\x1f.google.protobuf.MessageOptions\x18\xa0\xe03 \x01(\tR\x10tcaplusCipherMd5:S\n" +
	"\x14tcaplus_sharding_key\x12\x1f.google.protobuf.MessageOptions\x18\xa1\xe03 \x01(\tR\x12tcaplusShardingKey:P\n" +
	"\x12tcaplus_customattr\x12\x1f.google.protobuf.MessageOptions\x18\xa2\xe03 \x01(\tR\x11tcaplusCustomattr:B\n" +
	"\ftcaplus_size\x12\x1d.google.protobuf.FieldOptions\x18\x9c\xe03 \x01(\rR\vtcaplusSize:B\n" +
	"\ftcaplus_desc\x12\x1d.google.protobuf.FieldOptions\x18\x9d\xe03 \x01(\tR\vtcaplusDesc:F\n" +
	"\x0etcaplus_crypto\x12\x1d.google.protobuf.FieldOptions\x18\x9e\xe03 \x01(\bR\rtcaplusCrypto:7\n" +
	"\x05table\x12\x1f.google.protobuf.MessageOptions\x18\xfe\xd4\x03 \x01(\bR\x05table:>\n" +
	"\tnode_type\x12\x1f.google.protobuf.MessageOptions\x18\xff\xd4\x03 \x01(\tR\bnodeType:`\n" +
	"\x10table_store_mode\x12\x1f.google.protobuf.MessageOptions\x18\x80\xd5\x03 \x01(\x0e2\x13.orm.TableStoreModeR\x0etableStoreMode:3\n" +
	"\x04tags\x12\x1d.google.protobuf.FieldOptions\x18\xc3\xe03 \x01(\tR\x04tags:@\n" +
	"\vprimary_key\x12\x1d.google.protobuf.FieldOptions\x18\xc4\xe03 \x01(\bR\n" +
	"primaryKey:I\n" +
	"\x10skip_set_default\x12\x1d.google.protobuf.FieldOptions\x18\xc5\xe03 \x01(\bR\x0eskipSetDefault:5\n" +
	"\x05index\x12\x1d.google.protobuf.FieldOptions\x18\xc6\xe03 \x01(\bR\x05index:B\n" +
	"\fsharding_key\x12\x1d.google.protobuf.FieldOptions\x18\xc7\xe03 \x01(\bR\vshardingKey:>\n" +
	"\n" +
	"oneof_tags\x12\x1d.google.protobuf.OneofOptions\x18\xc3\xe03 \x01(\tR\toneofTagsB:Z8github.com/wxdqing/protoc-gen-go-orm.git/optionsb\x06proto3"

var (
	file_orm_option_proto_rawDescOnce sync.Once
	file_orm_option_proto_rawDescData []byte
)

func file_orm_option_proto_rawDescGZIP() []byte {
	file_orm_option_proto_rawDescOnce.Do(func() {
		file_orm_option_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orm_option_proto_rawDesc), len(file_orm_option_proto_rawDesc)))
	})
	return file_orm_option_proto_rawDescData
}

var file_orm_option_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_orm_option_proto_goTypes = []any{
	(TableStoreMode)(0),                 // 0: orm.TableStoreMode
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 2: google.protobuf.FieldOptions
	(*descriptorpb.OneofOptions)(nil),   // 3: google.protobuf.OneofOptions
}
var file_orm_option_proto_depIdxs = []int32{
	1,  // 0: orm.tcaplus_primary_key:extendee -> google.protobuf.MessageOptions
	1,  // 1: orm.tcaplus_index:extendee -> google.protobuf.MessageOptions
	1,  // 2: orm.tcaplus_field_cipher_suite:extendee -> google.protobuf.MessageOptions
	1,  // 3: orm.tcaplus_record_cipher_suite:extendee -> google.protobuf.MessageOptions
	1,  // 4: orm.tcaplus_cipher_md5:extendee -> google.protobuf.MessageOptions
	1,  // 5: orm.tcaplus_sharding_key:extendee -> google.protobuf.MessageOptions
	1,  // 6: orm.tcaplus_customattr:extendee -> google.protobuf.MessageOptions
	2,  // 7: orm.tcaplus_size:extendee -> google.protobuf.FieldOptions
	2,  // 8: orm.tcaplus_desc:extendee -> google.protobuf.FieldOptions
	2,  // 9: orm.tcaplus_crypto:extendee -> google.protobuf.FieldOptions
	1,  // 10: orm.table:extendee -> google.protobuf.MessageOptions
	1,  // 11: orm.node_type:extendee -> google.protobuf.MessageOptions
	1,  // 12: orm.table_store_mode:extendee -> google.protobuf.MessageOptions
	2,  // 13: orm.tags:extendee -> google.protobuf.FieldOptions
	2,  // 14: orm.primary_key:extendee -> google.protobuf.FieldOptions
	2,  // 15: orm.skip_set_default:extendee -> google.protobuf.FieldOptions
	2,  // 16: orm.index:extendee -> google.protobuf.FieldOptions
	2,  // 17: orm.sharding_key:extendee -> google.protobuf.FieldOptions
	3,  // 18: orm.oneof_tags:extendee -> google.protobuf.OneofOptions
	0,  // 19: orm.table_store_mode:type_name -> orm.TableStoreMode
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	19, // [19:20] is the sub-list for extension type_name
	0,  // [0:19] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_orm_option_proto_init() }
func file_orm_option_proto_init() {
	if File_orm_option_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orm_option_proto_rawDesc), len(file_orm_option_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 19,
			NumServices:   0,
		},
		GoTypes:           file_orm_option_proto_goTypes,
		DependencyIndexes: file_orm_option_proto_depIdxs,
		EnumInfos:         file_orm_option_proto_enumTypes,
		ExtensionInfos:    file_orm_option_proto_extTypes,
	}.Build()
	File_orm_option_proto = out.File
	file_orm_option_proto_goTypes = nil
	file_orm_option_proto_depIdxs = nil
}
