// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
//  protoc-gen-orm v0.1.0
//  protoc           v7.34.1
// dbType           mysql
// source: list.proto
// time 2026-06-04

package mysql

import (
	proto "google.golang.org/protobuf/proto"
)

type Context interface {
	Value(key any) any
}

type BeforeEncodeHook interface {
	BeforeEncode(ctx Context, value proto.Message) error
}

type AfterEncodeHook interface {
	AfterEncode(ctx Context, value proto.Message) error
}

type BeforeDecodeHook interface {
	BeforeDecode(ctx Context, value proto.Message) error
}

type AfterDecodeHook interface {
	AfterDecode(ctx Context, value proto.Message) error
}
