// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
//  protoc-gen-orm v0.1.0
//  protoc           v7.34.1
// dbType           mysql
// source: fields_player.proto
// time 2026-06-04

package mysql

import (
	proto "google.golang.org/protobuf/proto"
	reflect "reflect"
)

import "github.com/wxdqing/protoc-gen-go-orm/examples/src"

// methods for src.FieldsPlayer in mysql

func (m *FieldsPlayer) TableName() string {
	return "fields_player" //string(m.ProtoReflect().Descriptor().Name())
}

func (m *FieldsPlayer) NewValue() proto.Message {
	return &src.FieldsPlayer{}
}

func (m *FieldsPlayer) PrimaryKey() []any {
	return []any{m.Id}
}

func (m *FieldsPlayer) PrimaryKeyNames() []string {
	return []string{
		"id",
	}
}

func (m *FieldsPlayer) ToPrimaryKeyMap() map[string]any {
	ret := make(map[string]any)

	if !m.isZeroValue(m.Id) {
		ret["id"] = m.Id
	}

	return ret
}

func (m *FieldsPlayer) ToPrimaryKeyStruct() any {
	s := &FieldsPlayer{}

	if !m.isZeroValue(m.Id) {
		s.Id = m.Id
	}

	return s
}

func (m *FieldsPlayer) Indexes() []any {
	return []any{m.Name}
}

func (m *FieldsPlayer) IndexNames() []string {
	return []string{"name"}
}

func (m *FieldsPlayer) ToIndexMap() map[string]any {
	ret := map[string]any{}

	if !m.isZeroValue(m.Name) {
		ret["name"] = m.Name
	}

	return ret
}

func (m *FieldsPlayer) ToIndexStruct() any {
	s := &FieldsPlayer{}

	if !m.isZeroValue(m.Name) {
		s.Name = m.Name
	}

	return s
}

func (m *FieldsPlayer) isZeroValue(val any) bool {
	rv := reflect.ValueOf(val)
	return rv.IsZero() //|| rv.IsNil()
}

func (m *FieldsPlayer) EncodeFrom(value proto.Message) error {
	return m.EncodeFromContext(nil, value)
}

func (m *FieldsPlayer) EncodeFromContext(ctx Context, value proto.Message) error {
	if hook, ok := any(m).(BeforeEncodeHook); ok {
		if err := hook.BeforeEncode(ctx, value); err != nil {
			return err
		}
	}
	r := value.(*src.FieldsPlayer)
	m.Id = r.Id
	m.Name = r.Name
	m.Level = r.Level
	m.Exp = r.Exp
	m.PlayerEnum = int32(r.PlayerEnum)
	if b, err := marshalProtoFieldToWire(r.ProtoReflect(), "heros"); err != nil {
		return err
	} else if len(b) > 0 {
		m.Heros = b
	}
	if b, err := marshalProtoFieldToJSON(r.ProtoReflect(), "settings"); err != nil {
		return err
	} else if len(b) > 0 {
		m.Settings = b
	}

	if hook, ok := any(m).(AfterEncodeHook); ok {
		if err := hook.AfterEncode(ctx, value); err != nil {
			return err
		}
	}
	return nil
}

func (m *FieldsPlayer) DecodeTo(value proto.Message) error {
	return m.DecodeToContext(nil, value)
}

func (m *FieldsPlayer) DecodeToContext(ctx Context, value proto.Message) error {
	if hook, ok := any(m).(BeforeDecodeHook); ok {
		if err := hook.BeforeDecode(ctx, value); err != nil {
			return err
		}
	}
	r := value.(*src.FieldsPlayer)
	r.Id = m.Id
	r.Name = m.Name
	r.Level = m.Level
	r.Exp = m.Exp
	r.PlayerEnum = src.PlayerEnum(m.PlayerEnum)
	if len(m.Heros) > 0 {
		if err := unmarshalProtoFieldFromWire(r.ProtoReflect(), "heros", m.Heros); err != nil {
			return err
		}
	}
	if len(m.Settings) > 0 {
		if err := unmarshalProtoFieldFromJSON(r.ProtoReflect(), "settings", m.Settings); err != nil {
			return err
		}
	}

	src.SetFieldsPlayerDefaults(value.(*src.FieldsPlayer))
	if hook, ok := any(m).(AfterDecodeHook); ok {
		if err := hook.AfterDecode(ctx, value); err != nil {
			return err
		}
	}
	return nil
}
