// Code generated by protoc-gen-go-orm. DO NOT EDIT.
// versions:
//  protoc-gen-go-orm v0.1.0
//  protoc           v7.34.1
// source: fields_player.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: tb_fields_player.proto

package mysql

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MySQL表结构定义
type FieldsPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primary_key;column:id;autoIncrement:false;index:idx_fields_player_name;column:id"` //{ "pk":"primary_key;column:id;autoIncrement:false", "index":"index:idx_fields_player_name;column:id",   "origin":"id" }
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" gorm:"index:idx_fields_player_name;column:name"`                                      //{  "index":"index:idx_fields_player_name;column:name",   "origin":"name" }
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`                                                                                   //{     "origin":"level" }
	Exp           int64                  `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`                                                                                       //{     "origin":"exp" }
	Heros         []byte                 `protobuf:"bytes,5,opt,name=heros,proto3" json:"heros,omitempty" gorm:"type:blob;column:heros"`                                                      //{    "blob":"type:blob;column:heros", "origin":"heros" }
	Settings      []byte                 `protobuf:"bytes,7,opt,name=settings,proto3" json:"settings,omitempty" gorm:"type:json;column:settings;serializer:json"`                             //{   "json":"type:json;column:settings;serializer:json",  "origin":"settings" }
	PlayerEnum    int32                  `protobuf:"varint,9,opt,name=player_enum,json=playerEnum,proto3" json:"player_enum,omitempty"`                                                       //{     "origin":"player_enum" }
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldsPlayer) Reset() {
	*x = FieldsPlayer{}
	mi := &file_tb_fields_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldsPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldsPlayer) ProtoMessage() {}

func (x *FieldsPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_tb_fields_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldsPlayer.ProtoReflect.Descriptor instead.
func (*FieldsPlayer) Descriptor() ([]byte, []int) {
	return file_tb_fields_player_proto_rawDescGZIP(), []int{0}
}

func (x *FieldsPlayer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FieldsPlayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldsPlayer) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *FieldsPlayer) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *FieldsPlayer) GetHeros() []byte {
	if x != nil {
		return x.Heros
	}
	return nil
}

func (x *FieldsPlayer) GetSettings() []byte {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *FieldsPlayer) GetPlayerEnum() int32 {
	if x != nil {
		return x.PlayerEnum
	}
	return 0
}

var File_tb_fields_player_proto protoreflect.FileDescriptor

const file_tb_fields_player_proto_rawDesc = "" +
	"\n" +
	"\x16tb_fields_player.proto\x12\x05mysql\"\xad\x01\n" +
	"\fFieldsPlayer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\x03R\x03exp\x12\x14\n" +
	"\x05heros\x18\x05 \x01(\fR\x05heros\x12\x1a\n" +
	"\bsettings\x18\a \x01(\fR\bsettings\x12\x1f\n" +
	"\vplayer_enum\x18\t \x01(\x05R\n" +
	"playerEnumBBZ@github.com/wxdqing/protoc-gen-go-orm/examples/src/internal/mysqlb\x06proto3"

var (
	file_tb_fields_player_proto_rawDescOnce sync.Once
	file_tb_fields_player_proto_rawDescData []byte
)

func file_tb_fields_player_proto_rawDescGZIP() []byte {
	file_tb_fields_player_proto_rawDescOnce.Do(func() {
		file_tb_fields_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tb_fields_player_proto_rawDesc), len(file_tb_fields_player_proto_rawDesc)))
	})
	return file_tb_fields_player_proto_rawDescData
}

var file_tb_fields_player_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tb_fields_player_proto_goTypes = []any{
	(*FieldsPlayer)(nil), // 0: mysql.FieldsPlayer
}
var file_tb_fields_player_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tb_fields_player_proto_init() }
func file_tb_fields_player_proto_init() {
	if File_tb_fields_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tb_fields_player_proto_rawDesc), len(file_tb_fields_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tb_fields_player_proto_goTypes,
		DependencyIndexes: file_tb_fields_player_proto_depIdxs,
		MessageInfos:      file_tb_fields_player_proto_msgTypes,
	}.Build()
	File_tb_fields_player_proto = out.File
	file_tb_fields_player_proto_goTypes = nil
	file_tb_fields_player_proto_depIdxs = nil
}
