// Code generated by protoc-gen-go-orm. DO NOT EDIT.
// versions:
//  protoc-gen-go-orm v0.1.0
//  protoc           v7.34.1
// source: integration_game.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: tb_integration_game.proto

package mysql

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MySQL表结构定义
type GameRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      int64                  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty" gorm:"primary_key;column:server_id;autoIncrement:false;index:idx_game_role_server_name"` //{ "pk":"primary_key;column:server_id;autoIncrement:false", "index":"index:idx_game_role_server_name;column:server_id", "origin":"server_id" }
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty" gorm:"primary_key;column:role_id;autoIncrement:false"`                                         //{ "pk":"primary_key;column:role_id;autoIncrement:false", "origin":"role_id" }
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" gorm:"index:idx_game_role_server_name;column:name"`                                                               //{ "index":"index:idx_game_role_server_name;column:name", "origin":"name" }
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty" gorm:"index:idx_game_role_server_level;column:level"`                                                          //{ "index":"index:idx_game_role_server_level;column:level", "origin":"level" }
	Exp           int64                  `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`                                                                                                                   //{ "origin":"exp" }
	Heros         []byte                 `protobuf:"bytes,6,opt,name=heros,proto3" json:"heros,omitempty" gorm:"type:blob;column:heros"`                                                                                  //{ "blob":"type:blob;column:heros", "origin":"heros" }
	Timestamps    *RoleTimestamps        `protobuf:"bytes,7,opt,name=timestamps,proto3" json:"timestamps,omitempty" gorm:"embedded"`                                                                                      //{ "embedded":"embedded", "origin":"timestamps" }
	Settings      []byte                 `protobuf:"bytes,8,opt,name=settings,proto3" json:"settings,omitempty" gorm:"type:json;column:settings;serializer:json"`                                                         //{ "json":"type:json;column:settings;serializer:json", "origin":"settings" }
	PlayerEnum    int32                  `protobuf:"varint,9,opt,name=player_enum,json=playerEnum,proto3" json:"player_enum,omitempty"`                                                                                   //{ "origin":"player_enum" }
	Profile       []byte                 `protobuf:"bytes,10,opt,name=profile,proto3" json:"profile,omitempty"`                                                                                                           //{ "origin":"profile" }
	Version       int64                  `protobuf:"varint,11,opt,name=version,proto3" json:"version,omitempty"`                                                                                                          //{ "origin":"version" }
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRole) Reset() {
	*x = GameRole{}
	mi := &file_tb_integration_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRole) ProtoMessage() {}

func (x *GameRole) ProtoReflect() protoreflect.Message {
	mi := &file_tb_integration_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRole.ProtoReflect.Descriptor instead.
func (*GameRole) Descriptor() ([]byte, []int) {
	return file_tb_integration_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameRole) GetServerId() int64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *GameRole) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *GameRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameRole) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GameRole) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *GameRole) GetHeros() []byte {
	if x != nil {
		return x.Heros
	}
	return nil
}

func (x *GameRole) GetTimestamps() *RoleTimestamps {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *GameRole) GetSettings() []byte {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GameRole) GetPlayerEnum() int32 {
	if x != nil {
		return x.PlayerEnum
	}
	return 0
}

func (x *GameRole) GetProfile() []byte {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *GameRole) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// RoleHero
// MySQL表结构定义
type RoleHero struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                //{ "origin":"id" }
	Cid           int32                  `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`                              //{ "origin":"cid" }
	HeroLevel     int32                  `protobuf:"varint,3,opt,name=hero_level,json=heroLevel,proto3" json:"hero_level,omitempty"` //{ "origin":"hero_level" }
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleHero) Reset() {
	*x = RoleHero{}
	mi := &file_tb_integration_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleHero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleHero) ProtoMessage() {}

func (x *RoleHero) ProtoReflect() protoreflect.Message {
	mi := &file_tb_integration_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleHero.ProtoReflect.Descriptor instead.
func (*RoleHero) Descriptor() ([]byte, []int) {
	return file_tb_integration_game_proto_rawDescGZIP(), []int{1}
}

func (x *RoleHero) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleHero) GetCid() int32 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *RoleHero) GetHeroLevel() int32 {
	if x != nil {
		return x.HeroLevel
	}
	return 0
}

// RoleTimestamps
// MySQL表结构定义
type RoleTimestamps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     int64                  `protobuf:"varint,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" gorm:"autoCreateTime;<-:create"` //{ "custom":"autoCreateTime;<-:create", "origin":"created_at" }
	UpdatedAt     int64                  `protobuf:"varint,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" gorm:"autoUpdateTime"`           //{ "custom":"autoUpdateTime", "origin":"updated_at" }
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleTimestamps) Reset() {
	*x = RoleTimestamps{}
	mi := &file_tb_integration_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleTimestamps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleTimestamps) ProtoMessage() {}

func (x *RoleTimestamps) ProtoReflect() protoreflect.Message {
	mi := &file_tb_integration_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleTimestamps.ProtoReflect.Descriptor instead.
func (*RoleTimestamps) Descriptor() ([]byte, []int) {
	return file_tb_integration_game_proto_rawDescGZIP(), []int{2}
}

func (x *RoleTimestamps) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RoleTimestamps) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_tb_integration_game_proto protoreflect.FileDescriptor

const file_tb_integration_game_proto_rawDesc = "" +
	"\n" +
	"\x19tb_integration_game.proto\x12\x05mysql\"\xba\x02\n" +
	"\bGameRole\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x03R\bserverId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x03R\x06roleId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\x03R\x03exp\x12\x14\n" +
	"\x05heros\x18\x06 \x01(\fR\x05heros\x125\n" +
	"\n" +
	"timestamps\x18\a \x01(\v2\x15.mysql.RoleTimestampsR\n" +
	"timestamps\x12\x1a\n" +
	"\bsettings\x18\b \x01(\fR\bsettings\x12\x1f\n" +
	"\vplayer_enum\x18\t \x01(\x05R\n" +
	"playerEnum\x12\x18\n" +
	"\aprofile\x18\n" +
	" \x01(\fR\aprofile\x12\x18\n" +
	"\aversion\x18\v \x01(\x03R\aversion\"K\n" +
	"\bRoleHero\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\x05R\x03cid\x12\x1d\n" +
	"\n" +
	"hero_level\x18\x03 \x01(\x05R\theroLevel\"N\n" +
	"\x0eRoleTimestamps\x12\x1d\n" +
	"\n" +
	"created_at\x18\x01 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\x03R\tupdatedAtBBZ@github.com/wxdqing/protoc-gen-go-orm/examples/src/internal/mysqlb\x06proto3"

var (
	file_tb_integration_game_proto_rawDescOnce sync.Once
	file_tb_integration_game_proto_rawDescData []byte
)

func file_tb_integration_game_proto_rawDescGZIP() []byte {
	file_tb_integration_game_proto_rawDescOnce.Do(func() {
		file_tb_integration_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tb_integration_game_proto_rawDesc), len(file_tb_integration_game_proto_rawDesc)))
	})
	return file_tb_integration_game_proto_rawDescData
}

var file_tb_integration_game_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tb_integration_game_proto_goTypes = []any{
	(*GameRole)(nil),       // 0: mysql.GameRole
	(*RoleHero)(nil),       // 1: mysql.RoleHero
	(*RoleTimestamps)(nil), // 2: mysql.RoleTimestamps
}
var file_tb_integration_game_proto_depIdxs = []int32{
	2, // 0: mysql.GameRole.timestamps:type_name -> mysql.RoleTimestamps
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tb_integration_game_proto_init() }
func file_tb_integration_game_proto_init() {
	if File_tb_integration_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tb_integration_game_proto_rawDesc), len(file_tb_integration_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tb_integration_game_proto_goTypes,
		DependencyIndexes: file_tb_integration_game_proto_depIdxs,
		MessageInfos:      file_tb_integration_game_proto_msgTypes,
	}.Build()
	File_tb_integration_game_proto = out.File
	file_tb_integration_game_proto_goTypes = nil
	file_tb_integration_game_proto_depIdxs = nil
}
