// Code generated by protoc-gen-go-orm. DO NOT EDIT.
// versions:
//  protoc-gen-go-orm v0.1.0
//  protoc           v7.34.1
// source: list.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: tb_list.proto

package mysql

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lister
// MySQL表结构定义
type Lister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           int64                  `protobuf:"varint,1,opt,name=rid,proto3" json:"rid,omitempty" gorm:"primary_key;column:rid;autoIncrement:false;index:idx_lister_rid_id;column:rid"` //{ "pk":"primary_key;column:rid;autoIncrement:false", "index":"index:idx_lister_rid_id;column:rid",   "origin":"rid" }
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty" gorm:"primary_key;column:id;autoIncrement:false;index:idx_lister_rid_id;column:id"`     //{ "pk":"primary_key;column:id;autoIncrement:false", "index":"index:idx_lister_rid_id;column:id",   "origin":"id" }
	Data          []byte                 `protobuf:"bytes,999,opt,name=data,proto3" json:"data,omitempty" gorm:"column:data;type:blob"`
	CreatedAt     int64                  `protobuf:"varint,1000,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" gorm:"column:created_at;autoCreateTime;<-:create"`
	UpdatedAt     int64                  `protobuf:"varint,1001,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" gorm:"column:updated_at;autoUpdateTime"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lister) Reset() {
	*x = Lister{}
	mi := &file_tb_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lister) ProtoMessage() {}

func (x *Lister) ProtoReflect() protoreflect.Message {
	mi := &file_tb_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lister.ProtoReflect.Descriptor instead.
func (*Lister) Descriptor() ([]byte, []int) {
	return file_tb_list_proto_rawDescGZIP(), []int{0}
}

func (x *Lister) GetRid() int64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *Lister) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Lister) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Lister) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Lister) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_tb_list_proto protoreflect.FileDescriptor

const file_tb_list_proto_rawDesc = "" +
	"\n" +
	"\rtb_list.proto\x12\x05mysql\"\x7f\n" +
	"\x06Lister\x12\x10\n" +
	"\x03rid\x18\x01 \x01(\x03R\x03rid\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x13\n" +
	"\x04data\x18\xe7\a \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"created_at\x18\xe8\a \x01(\x03R\tcreatedAt\x12\x1e\n" +
	"\n" +
	"updated_at\x18\xe9\a \x01(\x03R\tupdatedAtBBZ@github.com/wxdqing/protoc-gen-go-orm/examples/src/internal/mysqlb\x06proto3"

var (
	file_tb_list_proto_rawDescOnce sync.Once
	file_tb_list_proto_rawDescData []byte
)

func file_tb_list_proto_rawDescGZIP() []byte {
	file_tb_list_proto_rawDescOnce.Do(func() {
		file_tb_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tb_list_proto_rawDesc), len(file_tb_list_proto_rawDesc)))
	})
	return file_tb_list_proto_rawDescData
}

var file_tb_list_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tb_list_proto_goTypes = []any{
	(*Lister)(nil), // 0: mysql.Lister
}
var file_tb_list_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tb_list_proto_init() }
func file_tb_list_proto_init() {
	if File_tb_list_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tb_list_proto_rawDesc), len(file_tb_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tb_list_proto_goTypes,
		DependencyIndexes: file_tb_list_proto_depIdxs,
		MessageInfos:      file_tb_list_proto_msgTypes,
	}.Build()
	File_tb_list_proto = out.File
	file_tb_list_proto_goTypes = nil
	file_tb_list_proto_depIdxs = nil
}
