// Code generated by protoc-gen-go-orm. DO NOT EDIT.
// versions:
//  protoc-gen-go-orm v0.1.0
//  protoc           v7.34.1
// source: players.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: tb_players.proto

package mysql

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Player
// MySQL表结构定义
type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primary_key;column:id;autoIncrement:false;index:idx_player_name;column:id"`      //{ "pk":"primary_key;column:id;autoIncrement:false", "index":"index:idx_player_name;column:id",   "origin":"id" }
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" gorm:"index:idx_player_name;column:name"`                                           //{  "index":"index:idx_player_name;column:name",   "origin":"name" }
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`                                                                                 //{     "origin":"level" }
	Exp           int64                  `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`                                                                                     //{     "origin":"exp" }// // heros is blob data in gorm
	Heros         []byte                 `protobuf:"bytes,5,opt,name=heros,proto3" json:"heros,omitempty" gorm:"type:blob;column:heros"`                                                    //{    "blob":"type:blob;column:heros", "origin":"heros" }
	BaseModel     *BaseModel             `protobuf:"bytes,6,opt,name=baseModel,proto3" json:"baseModel,omitempty"`                                                                          //{   "embedded":"embedded",  "origin":"baseModel" }
	Settings      []byte                 `protobuf:"bytes,7,opt,name=settings,proto3" json:"settings,omitempty" gorm:"type:json;column:settings;serializer:json"`                           //{   "json":"type:json;column:settings;serializer:json",  "origin":"settings" }
	Array         []byte                 `protobuf:"bytes,8,opt,name=array,proto3" json:"array,omitempty" gorm:"type:json;column:array;serializer:json"`                                    //{   "json":"type:json;column:array;serializer:json",  "origin":"array" }
	PlayerEnum    int32                  `protobuf:"varint,9,opt,name=player_enum,json=playerEnum,proto3" json:"player_enum,omitempty"`                                                     //{     "origin":"player_enum" }
	Enums         []byte                 `protobuf:"bytes,10,opt,name=enums,proto3" json:"enums,omitempty" gorm:"type:json;column:enums;serializer:json"`                                   //{   "json":"type:json;column:enums;serializer:json",  "origin":"enums" }
	Data          []byte                 `protobuf:"bytes,11,opt,name=data,proto3" json:"data,omitempty"`                                                                                   //{     "origin":"data" }
	Models        []byte                 `protobuf:"bytes,12,opt,name=models,proto3" json:"models,omitempty" gorm:"type:json;column:models;serializer:json"`                                //{   "json":"type:json;column:models;serializer:json",  "origin":"models" }
	SkipMe        []byte                 `protobuf:"bytes,13,opt,name=skip_me,json=skipMe,proto3" json:"skip_me,omitempty" gorm:"type:json;column:skip_me;serializer:json"`                 //{   "json":"type:json;column:skip_me;serializer:json",  "origin":"skip_me" }
	Nested        []byte                 `protobuf:"bytes,21,opt,name=nested,proto3" json:"nested,omitempty" gorm:"type:json;column:nested;serializer:json"`                                //{   "json":"type:json;column:nested;serializer:json",  "origin":"nested" }
	Nesteds       []byte                 `protobuf:"bytes,22,opt,name=nesteds,proto3" json:"nesteds,omitempty" gorm:"type:json;column:nesteds;serializer:json"`                             //{   "json":"type:json;column:nesteds;serializer:json",  "origin":"nesteds" }
	NestedMap     []byte                 `protobuf:"bytes,23,opt,name=nested_map,json=nestedMap,proto3" json:"nested_map,omitempty" gorm:"type:json;column:nested_map;serializer:json"`     //{   "json":"type:json;column:nested_map;serializer:json",  "origin":"nested_map" }
	Nested2       []byte                 `protobuf:"bytes,24,opt,name=nested2,proto3" json:"nested2,omitempty" gorm:"type:json;column:nested2;serializer:json"`                             //{   "json":"type:json;column:nested2;serializer:json",  "origin":"nested2" }
	N2S           []byte                 `protobuf:"bytes,25,opt,name=n2s,proto3" json:"n2s,omitempty" gorm:"type:json;column:n2s;serializer:json"`                                         //{   "json":"type:json;column:n2s;serializer:json",  "origin":"n2s" }
	Nested2Map    []byte                 `protobuf:"bytes,26,opt,name=nested2_map,json=nested2Map,proto3" json:"nested2_map,omitempty" gorm:"type:json;column:nested2_map;serializer:json"` //{   "json":"type:json;column:nested2_map;serializer:json",  "origin":"nested2_map" }
	Version       int64                  `protobuf:"varint,27,opt,name=version,proto3" json:"version,omitempty"`                                                                            //{     "origin":"version" }
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_tb_players_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_tb_players_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_tb_players_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Player) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *Player) GetHeros() []byte {
	if x != nil {
		return x.Heros
	}
	return nil
}

func (x *Player) GetBaseModel() *BaseModel {
	if x != nil {
		return x.BaseModel
	}
	return nil
}

func (x *Player) GetSettings() []byte {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Player) GetArray() []byte {
	if x != nil {
		return x.Array
	}
	return nil
}

func (x *Player) GetPlayerEnum() int32 {
	if x != nil {
		return x.PlayerEnum
	}
	return 0
}

func (x *Player) GetEnums() []byte {
	if x != nil {
		return x.Enums
	}
	return nil
}

func (x *Player) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Player) GetModels() []byte {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *Player) GetSkipMe() []byte {
	if x != nil {
		return x.SkipMe
	}
	return nil
}

func (x *Player) GetNested() []byte {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *Player) GetNesteds() []byte {
	if x != nil {
		return x.Nesteds
	}
	return nil
}

func (x *Player) GetNestedMap() []byte {
	if x != nil {
		return x.NestedMap
	}
	return nil
}

func (x *Player) GetNested2() []byte {
	if x != nil {
		return x.Nested2
	}
	return nil
}

func (x *Player) GetN2S() []byte {
	if x != nil {
		return x.N2S
	}
	return nil
}

func (x *Player) GetNested2Map() []byte {
	if x != nil {
		return x.Nested2Map
	}
	return nil
}

func (x *Player) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Hero
// MySQL表结构定义
type Hero struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,999,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,1000,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,1001,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hero) Reset() {
	*x = Hero{}
	mi := &file_tb_players_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hero) ProtoMessage() {}

func (x *Hero) ProtoReflect() protoreflect.Message {
	mi := &file_tb_players_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hero.ProtoReflect.Descriptor instead.
func (*Hero) Descriptor() ([]byte, []int) {
	return file_tb_players_proto_rawDescGZIP(), []int{1}
}

func (x *Hero) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Hero) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Hero) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// BaseModel
// MySQL表结构定义
type BaseModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,999,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,1000,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,1001,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseModel) Reset() {
	*x = BaseModel{}
	mi := &file_tb_players_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseModel) ProtoMessage() {}

func (x *BaseModel) ProtoReflect() protoreflect.Message {
	mi := &file_tb_players_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseModel.ProtoReflect.Descriptor instead.
func (*BaseModel) Descriptor() ([]byte, []int) {
	return file_tb_players_proto_rawDescGZIP(), []int{2}
}

func (x *BaseModel) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BaseModel) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *BaseModel) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_tb_players_proto protoreflect.FileDescriptor

const file_tb_players_proto_rawDesc = "" +
	"\n" +
	"\x10tb_players.proto\x12\x05mysql\"\x80\x04\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\x03R\x03exp\x12\x14\n" +
	"\x05heros\x18\x05 \x01(\fR\x05heros\x12.\n" +
	"\tbaseModel\x18\x06 \x01(\v2\x10.mysql.BaseModelR\tbaseModel\x12\x1a\n" +
	"\bsettings\x18\a \x01(\fR\bsettings\x12\x14\n" +
	"\x05array\x18\b \x01(\fR\x05array\x12\x1f\n" +
	"\vplayer_enum\x18\t \x01(\x05R\n" +
	"playerEnum\x12\x14\n" +
	"\x05enums\x18\n" +
	" \x01(\fR\x05enums\x12\x12\n" +
	"\x04data\x18\v \x01(\fR\x04data\x12\x16\n" +
	"\x06models\x18\f \x01(\fR\x06models\x12\x17\n" +
	"\askip_me\x18\r \x01(\fR\x06skipMe\x12\x16\n" +
	"\x06nested\x18\x15 \x01(\fR\x06nested\x12\x18\n" +
	"\anesteds\x18\x16 \x01(\fR\anesteds\x12\x1d\n" +
	"\n" +
	"nested_map\x18\x17 \x01(\fR\tnestedMap\x12\x18\n" +
	"\anested2\x18\x18 \x01(\fR\anested2\x12\x10\n" +
	"\x03n2s\x18\x19 \x01(\fR\x03n2s\x12\x1f\n" +
	"\vnested2_map\x18\x1a \x01(\fR\n" +
	"nested2Map\x12\x18\n" +
	"\aversion\x18\x1b \x01(\x03R\aversion\"[\n" +
	"\x04Hero\x12\x13\n" +
	"\x04data\x18\xe7\a \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"created_at\x18\xe8\a \x01(\x03R\tcreatedAt\x12\x1e\n" +
	"\n" +
	"updated_at\x18\xe9\a \x01(\x03R\tupdatedAt\"`\n" +
	"\tBaseModel\x12\x13\n" +
	"\x04data\x18\xe7\a \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"created_at\x18\xe8\a \x01(\x03R\tcreatedAt\x12\x1e\n" +
	"\n" +
	"updated_at\x18\xe9\a \x01(\x03R\tupdatedAtBBZ@github.com/wxdqing/protoc-gen-go-orm/examples/src/internal/mysqlb\x06proto3"

var (
	file_tb_players_proto_rawDescOnce sync.Once
	file_tb_players_proto_rawDescData []byte
)

func file_tb_players_proto_rawDescGZIP() []byte {
	file_tb_players_proto_rawDescOnce.Do(func() {
		file_tb_players_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tb_players_proto_rawDesc), len(file_tb_players_proto_rawDesc)))
	})
	return file_tb_players_proto_rawDescData
}

var file_tb_players_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tb_players_proto_goTypes = []any{
	(*Player)(nil),    // 0: mysql.Player
	(*Hero)(nil),      // 1: mysql.Hero
	(*BaseModel)(nil), // 2: mysql.BaseModel
}
var file_tb_players_proto_depIdxs = []int32{
	2, // 0: mysql.Player.baseModel:type_name -> mysql.BaseModel
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tb_players_proto_init() }
func file_tb_players_proto_init() {
	if File_tb_players_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tb_players_proto_rawDesc), len(file_tb_players_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tb_players_proto_goTypes,
		DependencyIndexes: file_tb_players_proto_depIdxs,
		MessageInfos:      file_tb_players_proto_msgTypes,
	}.Build()
	File_tb_players_proto = out.File
	file_tb_players_proto_goTypes = nil
	file_tb_players_proto_depIdxs = nil
}
