// Code generated by protoc-gen-go-orm. DO NOT EDIT.
// versions:
//  protoc-gen-go-orm v0.1.0
//  protoc           v7.34.1
// source: tables.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: tb_tables.proto

package mysql

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Example
// MySQL表结构定义
type Example struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WithNewTags     string                 `protobuf:"bytes,1,opt,name=with_new_tags,json=withNewTags,proto3" json:"with_new_tags,omitempty"`             //{ "origin":"with_new_tags" }
	WithNewMultiple string                 `protobuf:"bytes,2,opt,name=with_new_multiple,json=withNewMultiple,proto3" json:"with_new_multiple,omitempty"` //{ "origin":"with_new_multiple" }
	ReplaceDefault  string                 `protobuf:"bytes,3,opt,name=replace_default,json=replaceDefault,proto3" json:"replace_default,omitempty"`      //{ "origin":"replace_default" }
	Ll              []byte                 `protobuf:"bytes,7,opt,name=ll,proto3" json:"ll,omitempty" gorm:"type:json;column:ll;serializer:json"`         //{ "json":"type:json;column:ll;serializer:json", "origin":"ll" }
	Mm              []byte                 `protobuf:"bytes,8,opt,name=mm,proto3" json:"mm,omitempty" gorm:"type:json;column:mm;serializer:json"`         //{ "json":"type:json;column:mm;serializer:json", "origin":"mm" }
	Nn              []byte                 `protobuf:"bytes,9,opt,name=nn,proto3" json:"nn,omitempty" gorm:"type:json;column:nn;serializer:json"`         //{ "json":"type:json;column:nn;serializer:json", "origin":"nn" }
	Ee              []byte                 `protobuf:"bytes,10,opt,name=ee,proto3" json:"ee,omitempty" gorm:"type:json;column:ee;serializer:json"`        //{ "json":"type:json;column:ee;serializer:json", "origin":"ee" }
	Array           []byte                 `protobuf:"bytes,11,opt,name=array,proto3" json:"array,omitempty"`                                             //{ "origin":"array" }
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Example) Reset() {
	*x = Example{}
	mi := &file_tb_tables_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_tb_tables_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example.ProtoReflect.Descriptor instead.
func (*Example) Descriptor() ([]byte, []int) {
	return file_tb_tables_proto_rawDescGZIP(), []int{0}
}

func (x *Example) GetWithNewTags() string {
	if x != nil {
		return x.WithNewTags
	}
	return ""
}

func (x *Example) GetWithNewMultiple() string {
	if x != nil {
		return x.WithNewMultiple
	}
	return ""
}

func (x *Example) GetReplaceDefault() string {
	if x != nil {
		return x.ReplaceDefault
	}
	return ""
}

func (x *Example) GetLl() []byte {
	if x != nil {
		return x.Ll
	}
	return nil
}

func (x *Example) GetMm() []byte {
	if x != nil {
		return x.Mm
	}
	return nil
}

func (x *Example) GetNn() []byte {
	if x != nil {
		return x.Nn
	}
	return nil
}

func (x *Example) GetEe() []byte {
	if x != nil {
		return x.Ee
	}
	return nil
}

func (x *Example) GetArray() []byte {
	if x != nil {
		return x.Array
	}
	return nil
}

// SecondMessage
// MySQL表结构定义
type SecondMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WithNewTags     string                 `protobuf:"bytes,1,opt,name=with_new_tags,json=withNewTags,proto3" json:"with_new_tags,omitempty"`             //{ "origin":"with_new_tags" }
	WithNewMultiple string                 `protobuf:"bytes,2,opt,name=with_new_multiple,json=withNewMultiple,proto3" json:"with_new_multiple,omitempty"` //{ "origin":"with_new_multiple" }
	ReplaceDefault  string                 `protobuf:"bytes,3,opt,name=replace_default,json=replaceDefault,proto3" json:"replace_default,omitempty"`      //{ "origin":"replace_default" }
	InnerEnum       int32                  `protobuf:"varint,4,opt,name=inner_enum,json=innerEnum,proto3" json:"inner_enum,omitempty"`                    //{ "origin":"inner_enum" }
	OuterEnum       int32                  `protobuf:"varint,5,opt,name=outer_enum,json=outerEnum,proto3" json:"outer_enum,omitempty"`                    //{ "origin":"outer_enum" }
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SecondMessage) Reset() {
	*x = SecondMessage{}
	mi := &file_tb_tables_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecondMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecondMessage) ProtoMessage() {}

func (x *SecondMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tb_tables_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecondMessage.ProtoReflect.Descriptor instead.
func (*SecondMessage) Descriptor() ([]byte, []int) {
	return file_tb_tables_proto_rawDescGZIP(), []int{1}
}

func (x *SecondMessage) GetWithNewTags() string {
	if x != nil {
		return x.WithNewTags
	}
	return ""
}

func (x *SecondMessage) GetWithNewMultiple() string {
	if x != nil {
		return x.WithNewMultiple
	}
	return ""
}

func (x *SecondMessage) GetReplaceDefault() string {
	if x != nil {
		return x.ReplaceDefault
	}
	return ""
}

func (x *SecondMessage) GetInnerEnum() int32 {
	if x != nil {
		return x.InnerEnum
	}
	return 0
}

func (x *SecondMessage) GetOuterEnum() int32 {
	if x != nil {
		return x.OuterEnum
	}
	return 0
}

// ThirdExample
// MySQL表结构定义
type ThirdExample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InnerExample  []byte                 `protobuf:"bytes,1,opt,name=inner_example,json=innerExample,proto3" json:"inner_example,omitempty" gorm:"type:json;column:inner_example;serializer:json"` //{ "json":"type:json;column:inner_example;serializer:json", "origin":"inner_example" }
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdExample) Reset() {
	*x = ThirdExample{}
	mi := &file_tb_tables_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdExample) ProtoMessage() {}

func (x *ThirdExample) ProtoReflect() protoreflect.Message {
	mi := &file_tb_tables_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdExample.ProtoReflect.Descriptor instead.
func (*ThirdExample) Descriptor() ([]byte, []int) {
	return file_tb_tables_proto_rawDescGZIP(), []int{2}
}

func (x *ThirdExample) GetInnerExample() []byte {
	if x != nil {
		return x.InnerExample
	}
	return nil
}

// EmptyFieldMessage
// MySQL表结构定义
type EmptyFieldMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyFieldMessage) Reset() {
	*x = EmptyFieldMessage{}
	mi := &file_tb_tables_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyFieldMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyFieldMessage) ProtoMessage() {}

func (x *EmptyFieldMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tb_tables_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyFieldMessage.ProtoReflect.Descriptor instead.
func (*EmptyFieldMessage) Descriptor() ([]byte, []int) {
	return file_tb_tables_proto_rawDescGZIP(), []int{3}
}

var File_tb_tables_proto protoreflect.FileDescriptor

const file_tb_tables_proto_rawDesc = "" +
	"\n" +
	"\x0ftb_tables.proto\x12\x05mysql\"\xd8\x01\n" +
	"\aExample\x12\"\n" +
	"\rwith_new_tags\x18\x01 \x01(\tR\vwithNewTags\x12*\n" +
	"\x11with_new_multiple\x18\x02 \x01(\tR\x0fwithNewMultiple\x12'\n" +
	"\x0freplace_default\x18\x03 \x01(\tR\x0ereplaceDefault\x12\x0e\n" +
	"\x02ll\x18\a \x01(\fR\x02ll\x12\x0e\n" +
	"\x02mm\x18\b \x01(\fR\x02mm\x12\x0e\n" +
	"\x02nn\x18\t \x01(\fR\x02nn\x12\x0e\n" +
	"\x02ee\x18\n" +
	" \x01(\fR\x02ee\x12\x14\n" +
	"\x05array\x18\v \x01(\fR\x05array\"\xc6\x01\n" +
	"\rSecondMessage\x12\"\n" +
	"\rwith_new_tags\x18\x01 \x01(\tR\vwithNewTags\x12*\n" +
	"\x11with_new_multiple\x18\x02 \x01(\tR\x0fwithNewMultiple\x12'\n" +
	"\x0freplace_default\x18\x03 \x01(\tR\x0ereplaceDefault\x12\x1d\n" +
	"\n" +
	"inner_enum\x18\x04 \x01(\x05R\tinnerEnum\x12\x1d\n" +
	"\n" +
	"outer_enum\x18\x05 \x01(\x05R\touterEnum\"3\n" +
	"\fThirdExample\x12#\n" +
	"\rinner_example\x18\x01 \x01(\fR\finnerExample\"\x13\n" +
	"\x11EmptyFieldMessageBBZ@github.com/wxdqing/protoc-gen-go-orm/examples/src/internal/mysqlb\x06proto3"

var (
	file_tb_tables_proto_rawDescOnce sync.Once
	file_tb_tables_proto_rawDescData []byte
)

func file_tb_tables_proto_rawDescGZIP() []byte {
	file_tb_tables_proto_rawDescOnce.Do(func() {
		file_tb_tables_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tb_tables_proto_rawDesc), len(file_tb_tables_proto_rawDesc)))
	})
	return file_tb_tables_proto_rawDescData
}

var file_tb_tables_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tb_tables_proto_goTypes = []any{
	(*Example)(nil),           // 0: mysql.Example
	(*SecondMessage)(nil),     // 1: mysql.SecondMessage
	(*ThirdExample)(nil),      // 2: mysql.ThirdExample
	(*EmptyFieldMessage)(nil), // 3: mysql.EmptyFieldMessage
}
var file_tb_tables_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tb_tables_proto_init() }
func file_tb_tables_proto_init() {
	if File_tb_tables_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tb_tables_proto_rawDesc), len(file_tb_tables_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tb_tables_proto_goTypes,
		DependencyIndexes: file_tb_tables_proto_depIdxs,
		MessageInfos:      file_tb_tables_proto_msgTypes,
	}.Build()
	File_tb_tables_proto = out.File
	file_tb_tables_proto_goTypes = nil
	file_tb_tables_proto_depIdxs = nil
}
