// Code generated by protoc-gen-go-orm. DO NOT EDIT.
// versions:
//  protoc-gen-go-orm v0.1.0
//  protoc           v7.34.1
// source: tables.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: tb_tables.proto

package mysql

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_tb_tables_proto protoreflect.FileDescriptor

const file_tb_tables_proto_rawDesc = "" +
	"\n" +
	"\x0ftb_tables.proto\x12\x05mysqlBNZLgithub.com/wxdqing/protoc-gen-go-orm.git/examples/src/internal/mysqlb\x06proto3"

var file_tb_tables_proto_goTypes = []any{}
var file_tb_tables_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tb_tables_proto_init() }
func file_tb_tables_proto_init() {
	if File_tb_tables_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tb_tables_proto_rawDesc), len(file_tb_tables_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tb_tables_proto_goTypes,
		DependencyIndexes: file_tb_tables_proto_depIdxs,
	}.Build()
	File_tb_tables_proto = out.File
	file_tb_tables_proto_goTypes = nil
	file_tb_tables_proto_depIdxs = nil
}
