// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
//  protoc-gen-orm v0.1.0
//  protoc           v7.34.1
// dbType           pgsql
// source: integration_game.proto
// time 2026-06-05

package pgsql

import (
	proto "google.golang.org/protobuf/proto"
	reflect "reflect"
)

import "github.com/wxdqing/protoc-gen-go-orm/examples/src"

// methods for src.GameRole in pgsql

func (m *GameRole) TableName() string {
	return "game_role" //string(m.ProtoReflect().Descriptor().Name())
}

func (m *GameRole) NewValue() proto.Message {
	return &src.GameRole{}
}

func (m *GameRole) PrimaryKey() []any {
	return []any{m.ServerId, m.RoleId}
}

func (m *GameRole) PrimaryKeyNames() []string {
	return []string{
		"server_id", "role_id",
	}
}

func (m *GameRole) ToPrimaryKeyMap() map[string]any {
	ret := make(map[string]any)

	if !m.isZeroValue(m.ServerId) {
		ret["server_id"] = m.ServerId
	}
	if !m.isZeroValue(m.RoleId) {
		ret["role_id"] = m.RoleId
	}

	return ret
}

func (m *GameRole) ToPrimaryKeyStruct() any {
	s := &GameRole{}

	if !m.isZeroValue(m.ServerId) {
		s.ServerId = m.ServerId
	}
	if !m.isZeroValue(m.RoleId) {
		s.RoleId = m.RoleId
	}

	return s
}

func (m *GameRole) Indexes() []any {
	return []any{m.Name}
}

func (m *GameRole) IndexNames() []string {
	return []string{"name"}
}

func (m *GameRole) ToIndexMap() map[string]any {
	ret := map[string]any{}

	if !m.isZeroValue(m.Name) {
		ret["name"] = m.Name
	}

	return ret
}

func (m *GameRole) ToIndexStruct() any {
	s := &GameRole{}

	if !m.isZeroValue(m.Name) {
		s.Name = m.Name
	}

	return s
}

func (m *GameRole) isZeroValue(val any) bool {
	rv := reflect.ValueOf(val)
	return rv.IsZero() //|| rv.IsNil()
}

func (m *GameRole) EncodeFrom(value proto.Message) error {
	return m.EncodeFromContext(nil, value)
}

func (m *GameRole) EncodeFromContext(ctx Context, value proto.Message) error {
	if hook, ok := any(m).(BeforeEncodeHook); ok {
		if err := hook.BeforeEncode(ctx, value); err != nil {
			return err
		}
	}
	r := value.(*src.GameRole)
	m.ServerId = r.ServerId
	m.RoleId = r.RoleId
	m.Name = r.Name
	m.Level = r.Level
	m.Exp = r.Exp
	m.PlayerEnum = int32(r.PlayerEnum)
	m.Profile = r.Profile
	m.Version = r.Version
	if b, err := marshalProtoFieldToWire(r.ProtoReflect(), "heros"); err != nil {
		return err
	} else if len(b) > 0 {
		m.Heros = b
	}
	if r.Timestamps != nil {
		m.Timestamps = &RoleTimestamps{}
		if b, err := proto.Marshal(r.Timestamps); err != nil {
			return err
		} else if err := proto.Unmarshal(b, m.Timestamps); err != nil {
			return err
		}
	}
	if b, err := marshalProtoFieldToJSON(r.ProtoReflect(), "settings"); err != nil {
		return err
	} else if len(b) > 0 {
		m.Settings = b
	}
	vp := value.(interface {
		GetVersion() int64
	})
	m.Version = vp.GetVersion()
	if hook, ok := any(m).(AfterEncodeHook); ok {
		if err := hook.AfterEncode(ctx, value); err != nil {
			return err
		}
	}
	return nil
}

func (m *GameRole) DecodeTo(value proto.Message) error {
	return m.DecodeToContext(nil, value)
}

func (m *GameRole) DecodeToContext(ctx Context, value proto.Message) error {
	if hook, ok := any(m).(BeforeDecodeHook); ok {
		if err := hook.BeforeDecode(ctx, value); err != nil {
			return err
		}
	}
	r := value.(*src.GameRole)
	r.ServerId = m.ServerId
	r.RoleId = m.RoleId
	r.Name = m.Name
	r.Level = m.Level
	r.Exp = m.Exp
	r.PlayerEnum = src.PlayerEnum(m.PlayerEnum)
	r.Profile = m.Profile
	r.Version = m.Version
	if len(m.Heros) > 0 {
		if err := unmarshalProtoFieldFromWire(r.ProtoReflect(), "heros", m.Heros); err != nil {
			return err
		}
	}
	if m.Timestamps != nil {
		r.Timestamps = &src.RoleTimestamps{}
		if b, err := proto.Marshal(m.Timestamps); err != nil {
			return err
		} else if err := proto.Unmarshal(b, r.Timestamps); err != nil {
			return err
		}
	}
	if len(m.Settings) > 0 {
		if err := unmarshalProtoFieldFromJSON(r.ProtoReflect(), "settings", m.Settings); err != nil {
			return err
		}
	}
	vp := value.(interface {
		SetVersion(ver int64)
	})
	vp.SetVersion(m.Version)
	src.SetGameRoleDefaults(value.(*src.GameRole))
	if hook, ok := any(m).(AfterDecodeHook); ok {
		if err := hook.AfterDecode(ctx, value); err != nil {
			return err
		}
	}
	return nil
}

// SetVersion 设置GameRole的版本号
func (m *GameRole) SetVersion(ver int64) {
	if m == nil {
		return
	}
	m.Version = ver
}
