// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
//  protoc-gen-orm v0.1.0
//  protoc           v7.34.1
// dbType           pgsql
// source: players.proto
// time 2026-06-05

package pgsql

import (
	proto "google.golang.org/protobuf/proto"
	reflect "reflect"
)

import "github.com/wxdqing/protoc-gen-go-orm/examples/src"

// methods for src.Player in pgsql

func (m *Player) TableName() string {
	return "player" //string(m.ProtoReflect().Descriptor().Name())
}

func (m *Player) NewValue() proto.Message {
	return &src.Player{}
}

func (m *Player) PrimaryKey() []any {
	return []any{m.Id}
}

func (m *Player) PrimaryKeyNames() []string {
	return []string{
		"id",
	}
}

func (m *Player) ToPrimaryKeyMap() map[string]any {
	ret := make(map[string]any)

	if !m.isZeroValue(m.Id) {
		ret["id"] = m.Id
	}

	return ret
}

func (m *Player) ToPrimaryKeyStruct() any {
	s := &Player{}

	if !m.isZeroValue(m.Id) {
		s.Id = m.Id
	}

	return s
}

func (m *Player) Indexes() []any {
	return []any{m.Name}
}

func (m *Player) IndexNames() []string {
	return []string{"name"}
}

func (m *Player) ToIndexMap() map[string]any {
	ret := map[string]any{}

	if !m.isZeroValue(m.Name) {
		ret["name"] = m.Name
	}

	return ret
}

func (m *Player) ToIndexStruct() any {
	s := &Player{}

	if !m.isZeroValue(m.Name) {
		s.Name = m.Name
	}

	return s
}

func (m *Player) isZeroValue(val any) bool {
	rv := reflect.ValueOf(val)
	return rv.IsZero() //|| rv.IsNil()
}

func (m *Player) EncodeFrom(value proto.Message) error {
	return m.EncodeFromContext(nil, value)
}

func (m *Player) EncodeFromContext(ctx Context, value proto.Message) error {
	if hook, ok := any(m).(BeforeEncodeHook); ok {
		if err := hook.BeforeEncode(ctx, value); err != nil {
			return err
		}
	}
	r := value.(*src.Player)
	m.Id = r.Id
	m.Name = r.Name
	m.Level = r.Level
	m.Exp = r.Exp
	m.PlayerEnum = int32(r.PlayerEnum)
	m.Data = r.Data
	m.Version = r.Version
	if b, err := marshalProtoFieldToWire(r.ProtoReflect(), "heros"); err != nil {
		return err
	} else if len(b) > 0 {
		m.Heros = b
	}
	if r.BaseModel != nil {
		if m.BaseModel == nil {
			m.BaseModel = &BaseModel{}
		}
		m.BaseModel.CreatedAt = r.BaseModel.CreatedAt
		m.BaseModel.UpdatedAt = r.BaseModel.UpdatedAt
	}
	if b, err := marshalProtoFieldToJSON(r.ProtoReflect(), "settings"); err != nil {
		return err
	} else if len(b) > 0 {
		m.Settings = b
	}
	if b, err := marshalProtoFieldToJSON(r.ProtoReflect(), "array"); err != nil {
		return err
	} else if len(b) > 0 {
		m.Array = b
	}
	if b, err := marshalProtoFieldToJSON(r.ProtoReflect(), "enums"); err != nil {
		return err
	} else if len(b) > 0 {
		m.Enums = b
	}
	if b, err := marshalProtoFieldToJSON(r.ProtoReflect(), "models"); err != nil {
		return err
	} else if len(b) > 0 {
		m.Models = b
	}
	if b, err := marshalProtoFieldToJSON(r.ProtoReflect(), "skip_me"); err != nil {
		return err
	} else if len(b) > 0 {
		m.SkipMe = b
	}
	if b, err := marshalProtoFieldToJSON(r.ProtoReflect(), "nested"); err != nil {
		return err
	} else if len(b) > 0 {
		m.Nested = b
	}
	if b, err := marshalProtoFieldToJSON(r.ProtoReflect(), "nesteds"); err != nil {
		return err
	} else if len(b) > 0 {
		m.Nesteds = b
	}
	if b, err := marshalProtoFieldToJSON(r.ProtoReflect(), "nested_map"); err != nil {
		return err
	} else if len(b) > 0 {
		m.NestedMap = b
	}
	if b, err := marshalProtoFieldToJSON(r.ProtoReflect(), "nested2"); err != nil {
		return err
	} else if len(b) > 0 {
		m.Nested2 = b
	}
	if b, err := marshalProtoFieldToJSON(r.ProtoReflect(), "n2s"); err != nil {
		return err
	} else if len(b) > 0 {
		m.N2S = b
	}
	if b, err := marshalProtoFieldToJSON(r.ProtoReflect(), "nested2_map"); err != nil {
		return err
	} else if len(b) > 0 {
		m.Nested2Map = b
	}
	vp := value.(interface {
		GetVersion() int64
	})
	m.Version = vp.GetVersion()
	if hook, ok := any(m).(AfterEncodeHook); ok {
		if err := hook.AfterEncode(ctx, value); err != nil {
			return err
		}
	}
	return nil
}

func (m *Player) DecodeTo(value proto.Message) error {
	return m.DecodeToContext(nil, value)
}

func (m *Player) DecodeToContext(ctx Context, value proto.Message) error {
	if hook, ok := any(m).(BeforeDecodeHook); ok {
		if err := hook.BeforeDecode(ctx, value); err != nil {
			return err
		}
	}
	r := value.(*src.Player)
	r.Id = m.Id
	r.Name = m.Name
	r.Level = m.Level
	r.Exp = m.Exp
	r.PlayerEnum = src.PlayerEnum(m.PlayerEnum)
	r.Data = m.Data
	r.Version = m.Version
	if len(m.Heros) > 0 {
		if err := unmarshalProtoFieldFromWire(r.ProtoReflect(), "heros", m.Heros); err != nil {
			return err
		}
	}
	if m.BaseModel != nil {
		if r.BaseModel == nil {
			r.BaseModel = &src.BaseModel{}
		}
		r.BaseModel.CreatedAt = m.BaseModel.CreatedAt
		r.BaseModel.UpdatedAt = m.BaseModel.UpdatedAt
	}
	if len(m.Settings) > 0 {
		if err := unmarshalProtoFieldFromJSON(r.ProtoReflect(), "settings", m.Settings); err != nil {
			return err
		}
	}
	if len(m.Array) > 0 {
		if err := unmarshalProtoFieldFromJSON(r.ProtoReflect(), "array", m.Array); err != nil {
			return err
		}
	}
	if len(m.Enums) > 0 {
		if err := unmarshalProtoFieldFromJSON(r.ProtoReflect(), "enums", m.Enums); err != nil {
			return err
		}
	}
	if len(m.Models) > 0 {
		if err := unmarshalProtoFieldFromJSON(r.ProtoReflect(), "models", m.Models); err != nil {
			return err
		}
	}
	if len(m.SkipMe) > 0 {
		if err := unmarshalProtoFieldFromJSON(r.ProtoReflect(), "skip_me", m.SkipMe); err != nil {
			return err
		}
	}
	if len(m.Nested) > 0 {
		if err := unmarshalProtoFieldFromJSON(r.ProtoReflect(), "nested", m.Nested); err != nil {
			return err
		}
	}
	if len(m.Nesteds) > 0 {
		if err := unmarshalProtoFieldFromJSON(r.ProtoReflect(), "nesteds", m.Nesteds); err != nil {
			return err
		}
	}
	if len(m.NestedMap) > 0 {
		if err := unmarshalProtoFieldFromJSON(r.ProtoReflect(), "nested_map", m.NestedMap); err != nil {
			return err
		}
	}
	if len(m.Nested2) > 0 {
		if err := unmarshalProtoFieldFromJSON(r.ProtoReflect(), "nested2", m.Nested2); err != nil {
			return err
		}
	}
	if len(m.N2S) > 0 {
		if err := unmarshalProtoFieldFromJSON(r.ProtoReflect(), "n2s", m.N2S); err != nil {
			return err
		}
	}
	if len(m.Nested2Map) > 0 {
		if err := unmarshalProtoFieldFromJSON(r.ProtoReflect(), "nested2_map", m.Nested2Map); err != nil {
			return err
		}
	}
	vp := value.(interface {
		SetVersion(ver int64)
	})
	vp.SetVersion(m.Version)
	src.SetPlayerDefaults(value.(*src.Player))
	if hook, ok := any(m).(AfterDecodeHook); ok {
		if err := hook.AfterDecode(ctx, value); err != nil {
			return err
		}
	}
	return nil
}

// SetVersion 设置Player的版本号
func (m *Player) SetVersion(ver int64) {
	if m == nil {
		return
	}
	m.Version = ver
}
