// Code generated by protoc-gen-go-orm. DO NOT EDIT.
// versions:
//  protoc-gen-go-orm v0.1.0
//  protoc           v7.34.1
// source: players.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pg_players.proto

package pgsql

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Player
// PostgreSQL表结构定义
type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                        //{  "origin":"id" }
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                     //{  "origin":"name" }
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`                                                                  //{  "origin":"level" }
	Exp           int64                  `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`                                                                      //{  "origin":"exp" }// // heros is blob data in gorm
	Heros         []byte                 `protobuf:"bytes,5,opt,name=heros,proto3" json:"heros,omitempty" gorm:"type:jsonb;column:heros"`                                    //{ "json":"type:jsonb;column:heros", "origin":"heros" }
	BaseModel     []byte                 `protobuf:"bytes,6,opt,name=baseModel,proto3" json:"baseModel,omitempty" gorm:"type:jsonb;column:base_model"`                       //{ "json":"type:jsonb;column:base_model", "origin":"baseModel" }
	Settings      []byte                 `protobuf:"bytes,7,opt,name=settings,proto3" json:"settings,omitempty" gorm:"type:jsonb;column:settings"`                           //{ "json":"type:jsonb;column:settings", "origin":"settings" }
	Array         []byte                 `protobuf:"bytes,8,opt,name=array,proto3" json:"array,omitempty" gorm:"type:jsonb;column:array"`                                    //{ "json":"type:jsonb;column:array", "origin":"array" }
	PlayerEnum    int32                  `protobuf:"varint,9,opt,name=player_enum,json=playerEnum,proto3" json:"player_enum,omitempty"`                                      //{  "origin":"player_enum" }
	Enums         []byte                 `protobuf:"bytes,10,opt,name=enums,proto3" json:"enums,omitempty" gorm:"type:jsonb;column:enums"`                                   //{ "json":"type:jsonb;column:enums", "origin":"enums" }
	Data          []byte                 `protobuf:"bytes,11,opt,name=data,proto3" json:"data,omitempty"`                                                                    //{  "origin":"data" }
	Models        []byte                 `protobuf:"bytes,12,opt,name=models,proto3" json:"models,omitempty" gorm:"type:jsonb;column:models"`                                //{ "json":"type:jsonb;column:models", "origin":"models" }
	SkipMe        []byte                 `protobuf:"bytes,13,opt,name=skip_me,json=skipMe,proto3" json:"skip_me,omitempty" gorm:"type:jsonb;column:skip_me"`                 //{ "json":"type:jsonb;column:skip_me", "origin":"skip_me" }
	Nested        []byte                 `protobuf:"bytes,21,opt,name=nested,proto3" json:"nested,omitempty" gorm:"type:jsonb;column:nested"`                                //{ "json":"type:jsonb;column:nested", "origin":"nested" }
	Nesteds       []byte                 `protobuf:"bytes,22,opt,name=nesteds,proto3" json:"nesteds,omitempty" gorm:"type:jsonb;column:nesteds"`                             //{ "json":"type:jsonb;column:nesteds", "origin":"nesteds" }
	NestedMap     []byte                 `protobuf:"bytes,23,opt,name=nested_map,json=nestedMap,proto3" json:"nested_map,omitempty" gorm:"type:jsonb;column:nested_map"`     //{ "json":"type:jsonb;column:nested_map", "origin":"nested_map" }
	Nested2       []byte                 `protobuf:"bytes,24,opt,name=nested2,proto3" json:"nested2,omitempty" gorm:"type:jsonb;column:nested2"`                             //{ "json":"type:jsonb;column:nested2", "origin":"nested2" }
	N2S           []byte                 `protobuf:"bytes,25,opt,name=n2s,proto3" json:"n2s,omitempty" gorm:"type:jsonb;column:n2s"`                                         //{ "json":"type:jsonb;column:n2s", "origin":"n2s" }
	Nested2Map    []byte                 `protobuf:"bytes,26,opt,name=nested2_map,json=nested2Map,proto3" json:"nested2_map,omitempty" gorm:"type:jsonb;column:nested2_map"` //{ "json":"type:jsonb;column:nested2_map", "origin":"nested2_map" }
	Version       int64                  `protobuf:"varint,27,opt,name=version,proto3" json:"version,omitempty"`                                                             //{  "origin":"version" }
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_pg_players_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_pg_players_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_pg_players_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Player) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *Player) GetHeros() []byte {
	if x != nil {
		return x.Heros
	}
	return nil
}

func (x *Player) GetBaseModel() []byte {
	if x != nil {
		return x.BaseModel
	}
	return nil
}

func (x *Player) GetSettings() []byte {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Player) GetArray() []byte {
	if x != nil {
		return x.Array
	}
	return nil
}

func (x *Player) GetPlayerEnum() int32 {
	if x != nil {
		return x.PlayerEnum
	}
	return 0
}

func (x *Player) GetEnums() []byte {
	if x != nil {
		return x.Enums
	}
	return nil
}

func (x *Player) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Player) GetModels() []byte {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *Player) GetSkipMe() []byte {
	if x != nil {
		return x.SkipMe
	}
	return nil
}

func (x *Player) GetNested() []byte {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *Player) GetNesteds() []byte {
	if x != nil {
		return x.Nesteds
	}
	return nil
}

func (x *Player) GetNestedMap() []byte {
	if x != nil {
		return x.NestedMap
	}
	return nil
}

func (x *Player) GetNested2() []byte {
	if x != nil {
		return x.Nested2
	}
	return nil
}

func (x *Player) GetN2S() []byte {
	if x != nil {
		return x.N2S
	}
	return nil
}

func (x *Player) GetNested2Map() []byte {
	if x != nil {
		return x.Nested2Map
	}
	return nil
}

func (x *Player) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_pg_players_proto protoreflect.FileDescriptor

const file_pg_players_proto_rawDesc = "" +
	"\n" +
	"\x10pg_players.proto\x12\x05pgsql\"\xee\x03\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\x03R\x03exp\x12\x14\n" +
	"\x05heros\x18\x05 \x01(\fR\x05heros\x12\x1c\n" +
	"\tbaseModel\x18\x06 \x01(\fR\tbaseModel\x12\x1a\n" +
	"\bsettings\x18\a \x01(\fR\bsettings\x12\x14\n" +
	"\x05array\x18\b \x01(\fR\x05array\x12\x1f\n" +
	"\vplayer_enum\x18\t \x01(\x05R\n" +
	"playerEnum\x12\x14\n" +
	"\x05enums\x18\n" +
	" \x01(\fR\x05enums\x12\x12\n" +
	"\x04data\x18\v \x01(\fR\x04data\x12\x16\n" +
	"\x06models\x18\f \x01(\fR\x06models\x12\x17\n" +
	"\askip_me\x18\r \x01(\fR\x06skipMe\x12\x16\n" +
	"\x06nested\x18\x15 \x01(\fR\x06nested\x12\x18\n" +
	"\anesteds\x18\x16 \x01(\fR\anesteds\x12\x1d\n" +
	"\n" +
	"nested_map\x18\x17 \x01(\fR\tnestedMap\x12\x18\n" +
	"\anested2\x18\x18 \x01(\fR\anested2\x12\x10\n" +
	"\x03n2s\x18\x19 \x01(\fR\x03n2s\x12\x1f\n" +
	"\vnested2_map\x18\x1a \x01(\fR\n" +
	"nested2Map\x12\x18\n" +
	"\aversion\x18\x1b \x01(\x03R\aversionBNZLgithub.com/wxdqing/protoc-gen-go-orm.git/examples/src/internal/pgsqlb\x06proto3"

var (
	file_pg_players_proto_rawDescOnce sync.Once
	file_pg_players_proto_rawDescData []byte
)

func file_pg_players_proto_rawDescGZIP() []byte {
	file_pg_players_proto_rawDescOnce.Do(func() {
		file_pg_players_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pg_players_proto_rawDesc), len(file_pg_players_proto_rawDesc)))
	})
	return file_pg_players_proto_rawDescData
}

var file_pg_players_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pg_players_proto_goTypes = []any{
	(*Player)(nil), // 0: pgsql.Player
}
var file_pg_players_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pg_players_proto_init() }
func file_pg_players_proto_init() {
	if File_pg_players_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pg_players_proto_rawDesc), len(file_pg_players_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pg_players_proto_goTypes,
		DependencyIndexes: file_pg_players_proto_depIdxs,
		MessageInfos:      file_pg_players_proto_msgTypes,
	}.Build()
	File_pg_players_proto = out.File
	file_pg_players_proto_goTypes = nil
	file_pg_players_proto_depIdxs = nil
}
