// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
//  protoc-gen-orm v0.1.0
//  protoc           v7.34.1
// dbType           pgsql
// source: tables.proto
// time 2026-06-04

package pgsql
