// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
//  protoc-gen-orm v0.1.0
//  protoc           v7.34.1
// source: fields_player.proto
// time 2026-06-04

package src

import (
	proto "google.golang.org/protobuf/proto"
)

// GetFieldsPlayerTable 转换actor state为FieldsPlayer类型
func GetFieldsPlayerTable(holder interface{ GetStateValue() proto.Message }) *FieldsPlayer {
	return holder.GetStateValue().(*FieldsPlayer)
}

// ShardingKey 供 go-orm 分片路由（orm.ShardingKeyProvider）
func (x *FieldsPlayer) ShardingKey() int64 {
	return x.Id
}

func SetFieldsPlayerDefaults(r *FieldsPlayer) {
	if r == nil {
		return
	}
	if r.Heros == nil {
		r.Heros = make([]*Hero, 0)
	}
	if r.Settings == nil {
		r.Settings = make(map[string]int32)
	}

}
