// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: fields_player.proto

package src

import (
	_ "github.com/wxdqing/protoc-gen-go-orm/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 独立表名 fields_player，避免与 gs 示例 PAYLOAD 表 player 混用同一物理表。
type FieldsPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Exp           int64                  `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Heros         []*Hero                `protobuf:"bytes,5,rep,name=heros,proto3" json:"heros,omitempty"`
	Settings      map[string]int32       `protobuf:"bytes,7,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	PlayerEnum    PlayerEnum             `protobuf:"varint,9,opt,name=player_enum,json=playerEnum,proto3,enum=src.PlayerEnum" json:"player_enum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldsPlayer) Reset() {
	*x = FieldsPlayer{}
	mi := &file_fields_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldsPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldsPlayer) ProtoMessage() {}

func (x *FieldsPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_fields_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldsPlayer.ProtoReflect.Descriptor instead.
func (*FieldsPlayer) Descriptor() ([]byte, []int) {
	return file_fields_player_proto_rawDescGZIP(), []int{0}
}

func (x *FieldsPlayer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FieldsPlayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldsPlayer) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *FieldsPlayer) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *FieldsPlayer) GetHeros() []*Hero {
	if x != nil {
		return x.Heros
	}
	return nil
}

func (x *FieldsPlayer) GetSettings() map[string]int32 {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *FieldsPlayer) GetPlayerEnum() PlayerEnum {
	if x != nil {
		return x.PlayerEnum
	}
	return PlayerEnum_None
}

var File_fields_player_proto protoreflect.FileDescriptor

const file_fields_player_proto_rawDesc = "" +
	"\n" +
	"\x13fields_player.proto\x12\x03src\x1a\x10orm.option.proto\x1a\rplayers.proto\"\xde\x02\n" +
	"\fFieldsPlayer\x12\x15\n" +
	"\x02id\x18\x01 \x01(\x03B\x05\xa0\x84\x9e\x03\x01R\x02id\x12\x19\n" +
	"\x04name\x18\x02 \x01(\tB\x05\xb0\x84\x9e\x03\x01R\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\x03R\x03exp\x126\n" +
	"\x05heros\x18\x05 \x03(\v2\t.src.HeroB\x15\x9a\x84\x9e\x03\x10gorm:\"type:blob\"R\x05heros\x12;\n" +
	"\bsettings\x18\a \x03(\v2\x1f.src.FieldsPlayer.SettingsEntryR\bsettings\x120\n" +
	"\vplayer_enum\x18\t \x01(\x0e2\x0f.src.PlayerEnumR\n" +
	"playerEnum\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01:\x10\xf0\xa7\x1d\x01\xfa\xa7\x1d\x04game\x80\xa8\x1d\x01B3Z1github.com/wxdqing/protoc-gen-go-orm/examples/srcb\x06proto3"

var (
	file_fields_player_proto_rawDescOnce sync.Once
	file_fields_player_proto_rawDescData []byte
)

func file_fields_player_proto_rawDescGZIP() []byte {
	file_fields_player_proto_rawDescOnce.Do(func() {
		file_fields_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fields_player_proto_rawDesc), len(file_fields_player_proto_rawDesc)))
	})
	return file_fields_player_proto_rawDescData
}

var file_fields_player_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fields_player_proto_goTypes = []any{
	(*FieldsPlayer)(nil), // 0: src.FieldsPlayer
	nil,                  // 1: src.FieldsPlayer.SettingsEntry
	(*Hero)(nil),         // 2: src.Hero
	(PlayerEnum)(0),      // 3: src.PlayerEnum
}
var file_fields_player_proto_depIdxs = []int32{
	2, // 0: src.FieldsPlayer.heros:type_name -> src.Hero
	1, // 1: src.FieldsPlayer.settings:type_name -> src.FieldsPlayer.SettingsEntry
	3, // 2: src.FieldsPlayer.player_enum:type_name -> src.PlayerEnum
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_fields_player_proto_init() }
func file_fields_player_proto_init() {
	if File_fields_player_proto != nil {
		return
	}
	file_players_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fields_player_proto_rawDesc), len(file_fields_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fields_player_proto_goTypes,
		DependencyIndexes: file_fields_player_proto_depIdxs,
		MessageInfos:      file_fields_player_proto_msgTypes,
	}.Build()
	File_fields_player_proto = out.File
	file_fields_player_proto_goTypes = nil
	file_fields_player_proto_depIdxs = nil
}
