// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
//  protoc-gen-orm v0.1.0
//  protoc           v7.34.1
// source: integration_game.proto
// time 2026-06-05

package src

import (
	proto "google.golang.org/protobuf/proto"
)

func SetRoleHeroDefaults(r *RoleHero) {
	if r == nil {
		return
	}

}

func SetRoleTimestampsDefaults(r *RoleTimestamps) {
	if r == nil {
		return
	}

}

// GetGameRoleTable 转换actor state为GameRole类型
func GetGameRoleTable(holder interface{ GetStateValue() proto.Message }) *GameRole {
	return holder.GetStateValue().(*GameRole)
}

// SetVersion 设置GameRole的版本号
func (x *GameRole) SetVersion(ver int64) {
	if x == nil {
		return
	}
	x.Version = ver
}

// ShardingKey 供 go-orm 分片路由（orm.ShardingKeyProvider）
func (x *GameRole) ShardingKey() int64 {
	return x.ServerId
}

func SetGameRoleDefaults(r *GameRole) {
	if r == nil {
		return
	}
	if r.Heros == nil {
		r.Heros = make([]*RoleHero, 0)
	}
	if r.Timestamps == nil {
		r.Timestamps = &RoleTimestamps{}
		SetRoleTimestampsDefaults(r.Timestamps)
	}
	if r.Settings == nil {
		r.Settings = make(map[string]int32)
	}
	if r.Profile == nil {
		r.Profile = make([]byte, 0)
	}

}
