// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: integration_game.proto

package src

import (
	_ "github.com/wxdqing/protoc-gen-go-orm/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleHero struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cid           int32                  `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	HeroLevel     int32                  `protobuf:"varint,3,opt,name=hero_level,json=heroLevel,proto3" json:"hero_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleHero) Reset() {
	*x = RoleHero{}
	mi := &file_integration_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleHero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleHero) ProtoMessage() {}

func (x *RoleHero) ProtoReflect() protoreflect.Message {
	mi := &file_integration_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleHero.ProtoReflect.Descriptor instead.
func (*RoleHero) Descriptor() ([]byte, []int) {
	return file_integration_game_proto_rawDescGZIP(), []int{0}
}

func (x *RoleHero) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleHero) GetCid() int32 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *RoleHero) GetHeroLevel() int32 {
	if x != nil {
		return x.HeroLevel
	}
	return 0
}

type RoleTimestamps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     int64                  `protobuf:"varint,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleTimestamps) Reset() {
	*x = RoleTimestamps{}
	mi := &file_integration_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleTimestamps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleTimestamps) ProtoMessage() {}

func (x *RoleTimestamps) ProtoReflect() protoreflect.Message {
	mi := &file_integration_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleTimestamps.ProtoReflect.Descriptor instead.
func (*RoleTimestamps) Descriptor() ([]byte, []int) {
	return file_integration_game_proto_rawDescGZIP(), []int{1}
}

func (x *RoleTimestamps) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RoleTimestamps) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 集成测专用：复合主键 + 联合索引 + FIELDS 展开 + embed + blob/json。
type GameRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      int64                  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Exp           int64                  `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	Heros         []*RoleHero            `protobuf:"bytes,6,rep,name=heros,proto3" json:"heros,omitempty"`
	Timestamps    *RoleTimestamps        `protobuf:"bytes,7,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	Settings      map[string]int32       `protobuf:"bytes,8,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	PlayerEnum    PlayerEnum             `protobuf:"varint,9,opt,name=player_enum,json=playerEnum,proto3,enum=src.PlayerEnum" json:"player_enum,omitempty"`
	Profile       []byte                 `protobuf:"bytes,10,opt,name=profile,proto3" json:"profile,omitempty"`
	Version       int64                  `protobuf:"varint,11,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRole) Reset() {
	*x = GameRole{}
	mi := &file_integration_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRole) ProtoMessage() {}

func (x *GameRole) ProtoReflect() protoreflect.Message {
	mi := &file_integration_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRole.ProtoReflect.Descriptor instead.
func (*GameRole) Descriptor() ([]byte, []int) {
	return file_integration_game_proto_rawDescGZIP(), []int{2}
}

func (x *GameRole) GetServerId() int64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *GameRole) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *GameRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameRole) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GameRole) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *GameRole) GetHeros() []*RoleHero {
	if x != nil {
		return x.Heros
	}
	return nil
}

func (x *GameRole) GetTimestamps() *RoleTimestamps {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *GameRole) GetSettings() map[string]int32 {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GameRole) GetPlayerEnum() PlayerEnum {
	if x != nil {
		return x.PlayerEnum
	}
	return PlayerEnum_None
}

func (x *GameRole) GetProfile() []byte {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *GameRole) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_integration_game_proto protoreflect.FileDescriptor

const file_integration_game_proto_rawDesc = "" +
	"\n" +
	"\x16integration_game.proto\x12\x03src\x1a\x10orm.option.proto\x1a\rplayers.proto\"K\n" +
	"\bRoleHero\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\x05R\x03cid\x12\x1d\n" +
	"\n" +
	"hero_level\x18\x03 \x01(\x05R\theroLevel\"\x90\x01\n" +
	"\x0eRoleTimestamps\x12C\n" +
	"\n" +
	"created_at\x18\x01 \x01(\x03B$\x9a\x84\x9e\x03\x1fgorm:\"autoCreateTime;<-:create\"R\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\x03B\x1a\x9a\x84\x9e\x03\x15gorm:\"autoUpdateTime\"R\tupdatedAt\"\x94\x05\n" +
	"\bGameRole\x12\"\n" +
	"\tserver_id\x18\x01 \x01(\x03B\x05\xa0\x84\x9e\x03\x01R\bserverId\x12\x1e\n" +
	"\arole_id\x18\x02 \x01(\x03B\x05\xa0\x84\x9e\x03\x01R\x06roleId\x126\n" +
	"\x04name\x18\x03 \x01(\tB\"\x9a\x84\x9e\x03\x18gorm:\"size:128;not null\"\xb0\x84\x9e\x03\x01R\x04name\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\x03R\x03exp\x12:\n" +
	"\x05heros\x18\x06 \x03(\v2\r.src.RoleHeroB\x15\x9a\x84\x9e\x03\x10gorm:\"type:blob\"R\x05heros\x12I\n" +
	"\n" +
	"timestamps\x18\a \x01(\v2\x13.src.RoleTimestampsB\x14\x9a\x84\x9e\x03\x0fgorm:\"embedded\"R\n" +
	"timestamps\x127\n" +
	"\bsettings\x18\b \x03(\v2\x1b.src.GameRole.SettingsEntryR\bsettings\x120\n" +
	"\vplayer_enum\x18\t \x01(\x0e2\x0f.src.PlayerEnumR\n" +
	"playerEnum\x12-\n" +
	"\aprofile\x18\n" +
	" \x01(\fB\x13\x9a\x84\x9e\x03\x0ejson:\"profile\"R\aprofile\x12\x18\n" +
	"\aversion\x18\v \x01(\x03R\aversion\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01:l\xf0\xa7\x1d\x01\xfa\xa7\x1d\x04game\x80\xa8\x1d\x01\x8a\xa8\x1d)idx_game_role_server_name(server_id,name)\x8a\xa8\x1d+idx_game_role_server_level(server_id,level)B3Z1github.com/wxdqing/protoc-gen-go-orm/examples/srcb\x06proto3"

var (
	file_integration_game_proto_rawDescOnce sync.Once
	file_integration_game_proto_rawDescData []byte
)

func file_integration_game_proto_rawDescGZIP() []byte {
	file_integration_game_proto_rawDescOnce.Do(func() {
		file_integration_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_integration_game_proto_rawDesc), len(file_integration_game_proto_rawDesc)))
	})
	return file_integration_game_proto_rawDescData
}

var file_integration_game_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_integration_game_proto_goTypes = []any{
	(*RoleHero)(nil),       // 0: src.RoleHero
	(*RoleTimestamps)(nil), // 1: src.RoleTimestamps
	(*GameRole)(nil),       // 2: src.GameRole
	nil,                    // 3: src.GameRole.SettingsEntry
	(PlayerEnum)(0),        // 4: src.PlayerEnum
}
var file_integration_game_proto_depIdxs = []int32{
	0, // 0: src.GameRole.heros:type_name -> src.RoleHero
	1, // 1: src.GameRole.timestamps:type_name -> src.RoleTimestamps
	3, // 2: src.GameRole.settings:type_name -> src.GameRole.SettingsEntry
	4, // 3: src.GameRole.player_enum:type_name -> src.PlayerEnum
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_integration_game_proto_init() }
func file_integration_game_proto_init() {
	if File_integration_game_proto != nil {
		return
	}
	file_players_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_integration_game_proto_rawDesc), len(file_integration_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_integration_game_proto_goTypes,
		DependencyIndexes: file_integration_game_proto_depIdxs,
		MessageInfos:      file_integration_game_proto_msgTypes,
	}.Build()
	File_integration_game_proto = out.File
	file_integration_game_proto_goTypes = nil
	file_integration_game_proto_depIdxs = nil
}
