// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: list.proto

package src

import (
	_ "github.com/wxdqing/protoc-gen-go-orm/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           int64                  `protobuf:"varint,1,opt,name=rid,proto3" json:"rid,omitempty"` // 角色ID
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // 离线消息数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lister) Reset() {
	*x = Lister{}
	mi := &file_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lister) ProtoMessage() {}

func (x *Lister) ProtoReflect() protoreflect.Message {
	mi := &file_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lister.ProtoReflect.Descriptor instead.
func (*Lister) Descriptor() ([]byte, []int) {
	return file_list_proto_rawDescGZIP(), []int{0}
}

func (x *Lister) GetRid() int64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *Lister) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Lister) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_list_proto protoreflect.FileDescriptor

const file_list_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"list.proto\x12\x03src\x1a\x10orm.option.proto\"\x82\x01\n" +
	"\x06Lister\x12\x1c\n" +
	"\x03rid\x18\x01 \x01(\x03B\n" +
	"\xa0\x84\x9e\x03\x01\xb0\x84\x9e\x03\x01R\x03rid\x12\x15\n" +
	"\x02id\x18\x02 \x01(\x03B\x05\xa0\x84\x9e\x03\x01R\x02id\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data:/\xf0\xa7\x1d\x01\xfa\xa7\x1d\x06social\x80\xa8\x1d\x00\x8a\xa8\x1d\x19idx_lister_rid_id(rid,id)B3Z1github.com/wxdqing/protoc-gen-go-orm/examples/srcb\x06proto3"

var (
	file_list_proto_rawDescOnce sync.Once
	file_list_proto_rawDescData []byte
)

func file_list_proto_rawDescGZIP() []byte {
	file_list_proto_rawDescOnce.Do(func() {
		file_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_list_proto_rawDesc), len(file_list_proto_rawDesc)))
	})
	return file_list_proto_rawDescData
}

var file_list_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_list_proto_goTypes = []any{
	(*Lister)(nil), // 0: src.Lister
}
var file_list_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_list_proto_init() }
func file_list_proto_init() {
	if File_list_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_list_proto_rawDesc), len(file_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_list_proto_goTypes,
		DependencyIndexes: file_list_proto_depIdxs,
		MessageInfos:      file_list_proto_msgTypes,
	}.Build()
	File_list_proto = out.File
	file_list_proto_goTypes = nil
	file_list_proto_depIdxs = nil
}
