// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
//  protoc-gen-orm v0.1.0
//  protoc           v7.34.1
// source: list.proto
// time 2026-06-05

package src

import (
	proto "google.golang.org/protobuf/proto"
)

// GetListerTable 转换actor state为Lister类型
func GetListerTable(holder interface{ GetStateValue() proto.Message }) *Lister {
	return holder.GetStateValue().(*Lister)
}

// ShardingKey 供 go-orm 分片路由（orm.ShardingKeyProvider）
func (x *Lister) ShardingKey() int64 {
	return x.Rid
}

func SetListerDefaults(r *Lister) {
	if r == nil {
		return
	}
	if r.Data == nil {
		r.Data = make([]byte, 0)
	}

}
