// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: players.proto

package src

import (
	_ "github.com/wxdqing/protoc-gen-go-orm/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerEnum int32

const (
	PlayerEnum_None  PlayerEnum = 0
	PlayerEnum_Test1 PlayerEnum = 1
	PlayerEnum_Test2 PlayerEnum = 2
)

// Enum value maps for PlayerEnum.
var (
	PlayerEnum_name = map[int32]string{
		0: "None",
		1: "Test1",
		2: "Test2",
	}
	PlayerEnum_value = map[string]int32{
		"None":  0,
		"Test1": 1,
		"Test2": 2,
	}
)

func (x PlayerEnum) Enum() *PlayerEnum {
	p := new(PlayerEnum)
	*p = x
	return p
}

func (x PlayerEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_players_proto_enumTypes[0].Descriptor()
}

func (PlayerEnum) Type() protoreflect.EnumType {
	return &file_players_proto_enumTypes[0]
}

func (x PlayerEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerEnum.Descriptor instead.
func (PlayerEnum) EnumDescriptor() ([]byte, []int) {
	return file_players_proto_rawDescGZIP(), []int{0}
}

type Player struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Exp   int64                  `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	// heros is blob data in gorm
	Heros         []*Hero                            `protobuf:"bytes,5,rep,name=heros,proto3" json:"heros,omitempty"`
	BaseModel     *BaseModel                         `protobuf:"bytes,6,opt,name=baseModel,proto3" json:"baseModel,omitempty"`
	Settings      map[string]int32                   `protobuf:"bytes,7,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Array         []int32                            `protobuf:"varint,8,rep,packed,name=array,proto3" json:"array,omitempty"`
	PlayerEnum    PlayerEnum                         `protobuf:"varint,9,opt,name=player_enum,json=playerEnum,proto3,enum=src.PlayerEnum" json:"player_enum,omitempty"`
	Enums         []PlayerEnum                       `protobuf:"varint,10,rep,packed,name=enums,proto3,enum=src.PlayerEnum" json:"enums,omitempty"`
	Data          []byte                             `protobuf:"bytes,11,opt,name=data,proto3" json:"data,omitempty"`
	Models        map[int32]*BaseModel               `protobuf:"bytes,12,rep,name=models,proto3" json:"models,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SkipMe        *BaseModel                         `protobuf:"bytes,13,opt,name=skip_me,json=skipMe,proto3" json:"skip_me,omitempty"`
	Nested        *Player_NestedM                    `protobuf:"bytes,21,opt,name=nested,proto3" json:"nested,omitempty"`
	Nesteds       []*Player_NestedM                  `protobuf:"bytes,22,rep,name=nesteds,proto3" json:"nesteds,omitempty"`
	NestedMap     map[string]*Player_NestedM         `protobuf:"bytes,23,rep,name=nested_map,json=nestedMap,proto3" json:"nested_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Nested2       *Player_NestedM_Nested2            `protobuf:"bytes,24,opt,name=nested2,proto3" json:"nested2,omitempty"`
	N2S           []*Player_NestedM_Nested2          `protobuf:"bytes,25,rep,name=n2s,proto3" json:"n2s,omitempty"`
	Nested2Map    map[string]*Player_NestedM_Nested2 `protobuf:"bytes,26,rep,name=nested2_map,json=nested2Map,proto3" json:"nested2_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version       int64                              `protobuf:"varint,27,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_players_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_players_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_players_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Player) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *Player) GetHeros() []*Hero {
	if x != nil {
		return x.Heros
	}
	return nil
}

func (x *Player) GetBaseModel() *BaseModel {
	if x != nil {
		return x.BaseModel
	}
	return nil
}

func (x *Player) GetSettings() map[string]int32 {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Player) GetArray() []int32 {
	if x != nil {
		return x.Array
	}
	return nil
}

func (x *Player) GetPlayerEnum() PlayerEnum {
	if x != nil {
		return x.PlayerEnum
	}
	return PlayerEnum_None
}

func (x *Player) GetEnums() []PlayerEnum {
	if x != nil {
		return x.Enums
	}
	return nil
}

func (x *Player) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Player) GetModels() map[int32]*BaseModel {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *Player) GetSkipMe() *BaseModel {
	if x != nil {
		return x.SkipMe
	}
	return nil
}

func (x *Player) GetNested() *Player_NestedM {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *Player) GetNesteds() []*Player_NestedM {
	if x != nil {
		return x.Nesteds
	}
	return nil
}

func (x *Player) GetNestedMap() map[string]*Player_NestedM {
	if x != nil {
		return x.NestedMap
	}
	return nil
}

func (x *Player) GetNested2() *Player_NestedM_Nested2 {
	if x != nil {
		return x.Nested2
	}
	return nil
}

func (x *Player) GetN2S() []*Player_NestedM_Nested2 {
	if x != nil {
		return x.N2S
	}
	return nil
}

func (x *Player) GetNested2Map() map[string]*Player_NestedM_Nested2 {
	if x != nil {
		return x.Nested2Map
	}
	return nil
}

func (x *Player) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Hero struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cid           int32                  `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	HeroLevel     int32                  `protobuf:"varint,3,opt,name=hero_level,json=heroLevel,proto3" json:"hero_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hero) Reset() {
	*x = Hero{}
	mi := &file_players_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hero) ProtoMessage() {}

func (x *Hero) ProtoReflect() protoreflect.Message {
	mi := &file_players_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hero.ProtoReflect.Descriptor instead.
func (*Hero) Descriptor() ([]byte, []int) {
	return file_players_proto_rawDescGZIP(), []int{1}
}

func (x *Hero) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Hero) GetCid() int32 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *Hero) GetHeroLevel() int32 {
	if x != nil {
		return x.HeroLevel
	}
	return 0
}

type BaseModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     int64                  `protobuf:"varint,1,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,2,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseModel) Reset() {
	*x = BaseModel{}
	mi := &file_players_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseModel) ProtoMessage() {}

func (x *BaseModel) ProtoReflect() protoreflect.Message {
	mi := &file_players_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseModel.ProtoReflect.Descriptor instead.
func (*BaseModel) Descriptor() ([]byte, []int) {
	return file_players_proto_rawDescGZIP(), []int{2}
}

func (x *BaseModel) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *BaseModel) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type Player_NestedM struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	F1            int64                              `protobuf:"varint,1,opt,name=f1,proto3" json:"f1,omitempty"`
	F2            string                             `protobuf:"bytes,2,opt,name=f2,proto3" json:"f2,omitempty"`
	F3            map[string]int32                   `protobuf:"bytes,3,rep,name=f3,proto3" json:"f3,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	F4            *Player_NestedM_Nested2            `protobuf:"bytes,4,opt,name=f4,proto3" json:"f4,omitempty"`
	F5            map[string]*Player_NestedM_Nested2 `protobuf:"bytes,5,rep,name=f5,proto3" json:"f5,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	F6            []*Player_NestedM_Nested2          `protobuf:"bytes,6,rep,name=f6,proto3" json:"f6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player_NestedM) Reset() {
	*x = Player_NestedM{}
	mi := &file_players_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player_NestedM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player_NestedM) ProtoMessage() {}

func (x *Player_NestedM) ProtoReflect() protoreflect.Message {
	mi := &file_players_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player_NestedM.ProtoReflect.Descriptor instead.
func (*Player_NestedM) Descriptor() ([]byte, []int) {
	return file_players_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Player_NestedM) GetF1() int64 {
	if x != nil {
		return x.F1
	}
	return 0
}

func (x *Player_NestedM) GetF2() string {
	if x != nil {
		return x.F2
	}
	return ""
}

func (x *Player_NestedM) GetF3() map[string]int32 {
	if x != nil {
		return x.F3
	}
	return nil
}

func (x *Player_NestedM) GetF4() *Player_NestedM_Nested2 {
	if x != nil {
		return x.F4
	}
	return nil
}

func (x *Player_NestedM) GetF5() map[string]*Player_NestedM_Nested2 {
	if x != nil {
		return x.F5
	}
	return nil
}

func (x *Player_NestedM) GetF6() []*Player_NestedM_Nested2 {
	if x != nil {
		return x.F6
	}
	return nil
}

type Player_NestedM_Nested2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	F1            int64                  `protobuf:"varint,1,opt,name=f1,proto3" json:"f1,omitempty"`
	F2            string                 `protobuf:"bytes,2,opt,name=f2,proto3" json:"f2,omitempty"`
	F3            map[string]int32       `protobuf:"bytes,3,rep,name=f3,proto3" json:"f3,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player_NestedM_Nested2) Reset() {
	*x = Player_NestedM_Nested2{}
	mi := &file_players_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player_NestedM_Nested2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player_NestedM_Nested2) ProtoMessage() {}

func (x *Player_NestedM_Nested2) ProtoReflect() protoreflect.Message {
	mi := &file_players_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player_NestedM_Nested2.ProtoReflect.Descriptor instead.
func (*Player_NestedM_Nested2) Descriptor() ([]byte, []int) {
	return file_players_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *Player_NestedM_Nested2) GetF1() int64 {
	if x != nil {
		return x.F1
	}
	return 0
}

func (x *Player_NestedM_Nested2) GetF2() string {
	if x != nil {
		return x.F2
	}
	return ""
}

func (x *Player_NestedM_Nested2) GetF3() map[string]int32 {
	if x != nil {
		return x.F3
	}
	return nil
}

var File_players_proto protoreflect.FileDescriptor

const file_players_proto_rawDesc = "" +
	"\n" +
	"\rplayers.proto\x12\x03src\x1a\x10orm.option.proto\"\xcb\x11\n" +
	"\x06Player\x12]\n" +
	"\x02id\x18\x01 \x01(\x03BM\x9a\x84\x9e\x03Cgorm:\"column:id;primary_key;<-:create;autoIncrement:true\" json:\"id\"\xa0\x84\x9e\x03\x01R\x02id\x12H\n" +
	"\x04name\x18\x02 \x01(\tB4\x9a\x84\x9e\x03*gorm:\"size:255;index;not null\" json:\"name\"\xb0\x84\x9e\x03\x01R\x04name\x128\n" +
	"\x05level\x18\x03 \x01(\x05B\"\x9a\x84\x9e\x03\x1dgorm:\"default:1\" json:\"level\"R\x05level\x122\n" +
	"\x03exp\x18\x04 \x01(\x03B \x9a\x84\x9e\x03\x1bgorm:\"default:0\" json:\"exp\"R\x03exp\x12C\n" +
	"\x05heros\x18\x05 \x03(\v2\t.src.HeroB\"\x9a\x84\x9e\x03\x1dgorm:\"type:blob\" json:\"heros\"R\x05heros\x12B\n" +
	"\tbaseModel\x18\x06 \x01(\v2\x0e.src.BaseModelB\x14\x9a\x84\x9e\x03\x0fgorm:\"embedded\"R\tbaseModel\x125\n" +
	"\bsettings\x18\a \x03(\v2\x19.src.Player.SettingsEntryR\bsettings\x12\x14\n" +
	"\x05array\x18\b \x03(\x05R\x05array\x12H\n" +
	"\vplayer_enum\x18\t \x01(\x0e2\x0f.src.PlayerEnumB\x16\x9a\x84\x9e\x03\x11json:\"playerEnum\"R\n" +
	"playerEnum\x128\n" +
	"\x05enums\x18\n" +
	" \x03(\x0e2\x0f.src.PlayerEnumB\x11\x9a\x84\x9e\x03\fjson:\"enums\"R\x05enums\x12$\n" +
	"\x04data\x18\v \x01(\fB\x10\x9a\x84\x9e\x03\vjson:\"data\"R\x04data\x12C\n" +
	"\x06models\x18\f \x03(\v2\x17.src.Player.ModelsEntryB\x12\x9a\x84\x9e\x03\rjson:\"models\"R\x06models\x124\n" +
	"\askip_me\x18\r \x01(\v2\x0e.src.BaseModelB\v\x9a\x84\x9e\x03\x01-\xa8\x84\x9e\x03\x01R\x06skipMe\x12?\n" +
	"\x06nested\x18\x15 \x01(\v2\x13.src.Player.NestedMB\x12\x9a\x84\x9e\x03\rjson:\"nested\"R\x06nested\x12B\n" +
	"\anesteds\x18\x16 \x03(\v2\x13.src.Player.NestedMB\x13\x9a\x84\x9e\x03\x0ejson:\"nesteds\"R\anesteds\x12P\n" +
	"\n" +
	"nested_map\x18\x17 \x03(\v2\x1a.src.Player.NestedMapEntryB\x15\x9a\x84\x9e\x03\x10json:\"nestedMap\"R\tnestedMap\x12J\n" +
	"\anested2\x18\x18 \x01(\v2\x1b.src.Player.NestedM.Nested2B\x13\x9a\x84\x9e\x03\x0ejson:\"nested2\"R\anested2\x12C\n" +
	"\x03n2s\x18\x19 \x03(\v2\x1b.src.Player.NestedM.Nested2B\x14\x9a\x84\x9e\x03\x0fjson:\"nested2s\"R\x03n2s\x12T\n" +
	"\vnested2_map\x18\x1a \x03(\v2\x1b.src.Player.Nested2MapEntryB\x16\x9a\x84\x9e\x03\x11json:\"nested2Map\"R\n" +
	"nested2Map\x12\x18\n" +
	"\aversion\x18\x1b \x01(\x03R\aversion\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aI\n" +
	"\vModelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.src.BaseModelR\x05value:\x028\x01\x1a\x80\x04\n" +
	"\aNestedM\x12\x0e\n" +
	"\x02f1\x18\x01 \x01(\x03R\x02f1\x12\x0e\n" +
	"\x02f2\x18\x02 \x01(\tR\x02f2\x12+\n" +
	"\x02f3\x18\x03 \x03(\v2\x1b.src.Player.NestedM.F3EntryR\x02f3\x12+\n" +
	"\x02f4\x18\x04 \x01(\v2\x1b.src.Player.NestedM.Nested2R\x02f4\x12+\n" +
	"\x02f5\x18\x05 \x03(\v2\x1b.src.Player.NestedM.F5EntryR\x02f5\x12+\n" +
	"\x02f6\x18\x06 \x03(\v2\x1b.src.Player.NestedM.Nested2R\x02f6\x1a\x95\x01\n" +
	"\aNested2\x12\x0e\n" +
	"\x02f1\x18\x01 \x01(\x03R\x02f1\x12\x0e\n" +
	"\x02f2\x18\x02 \x01(\tR\x02f2\x123\n" +
	"\x02f3\x18\x03 \x03(\v2#.src.Player.NestedM.Nested2.F3EntryR\x02f3\x1a5\n" +
	"\aF3Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a5\n" +
	"\aF3Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aR\n" +
	"\aF5Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.src.Player.NestedM.Nested2R\x05value:\x028\x01\x1aQ\n" +
	"\x0eNestedMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.src.Player.NestedMR\x05value:\x028\x01\x1aZ\n" +
	"\x0fNested2MapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.src.Player.NestedM.Nested2R\x05value:\x028\x01:\x96\x01\xf0\xa7\x1d\x01\xfa\xa7\x1d\x04game\x80\xa8\x1d\x01⁞\x03\x02idꁞ\x03\tlevel,exp\xf2\x81\x9e\x03\x13default_field_suite\xfa\x81\x9e\x03\x14default_record_suite\x82\x82\x9e\x03 d41d8cd98f00b204e9800998ecf8427e\x92\x82\x9e\x03\x16custom_attribute_valueJ\x04\b\x0e\x10\x15\"^\n" +
	"\x04Hero\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\x05R\x03cid\x124\n" +
	"\n" +
	"hero_level\x18\x03 \x01(\x05B\x15\x9a\x84\x9e\x03\x10json:\"heroLevel\"R\theroLevel\"\xab\x01\n" +
	"\tBaseModel\x12S\n" +
	"\tCreatedAt\x18\x01 \x01(\x03B5\x9a\x84\x9e\x030gorm:\"autoCreateTime;<-:create\" json:\"createdAt\"R\tCreatedAt\x12I\n" +
	"\tUpdatedAt\x18\x02 \x01(\x03B+\x9a\x84\x9e\x03&gorm:\"autoUpdateTime\" json:\"updatedAt\"R\tUpdatedAt*,\n" +
	"\n" +
	"PlayerEnum\x12\b\n" +
	"\x04None\x10\x00\x12\t\n" +
	"\x05Test1\x10\x01\x12\t\n" +
	"\x05Test2\x10\x02B3Z1github.com/wxdqing/protoc-gen-go-orm/examples/srcb\x06proto3"

var (
	file_players_proto_rawDescOnce sync.Once
	file_players_proto_rawDescData []byte
)

func file_players_proto_rawDescGZIP() []byte {
	file_players_proto_rawDescOnce.Do(func() {
		file_players_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_players_proto_rawDesc), len(file_players_proto_rawDesc)))
	})
	return file_players_proto_rawDescData
}

var file_players_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_players_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_players_proto_goTypes = []any{
	(PlayerEnum)(0),                // 0: src.PlayerEnum
	(*Player)(nil),                 // 1: src.Player
	(*Hero)(nil),                   // 2: src.Hero
	(*BaseModel)(nil),              // 3: src.BaseModel
	nil,                            // 4: src.Player.SettingsEntry
	nil,                            // 5: src.Player.ModelsEntry
	(*Player_NestedM)(nil),         // 6: src.Player.NestedM
	nil,                            // 7: src.Player.NestedMapEntry
	nil,                            // 8: src.Player.Nested2MapEntry
	(*Player_NestedM_Nested2)(nil), // 9: src.Player.NestedM.Nested2
	nil,                            // 10: src.Player.NestedM.F3Entry
	nil,                            // 11: src.Player.NestedM.F5Entry
	nil,                            // 12: src.Player.NestedM.Nested2.F3Entry
}
var file_players_proto_depIdxs = []int32{
	2,  // 0: src.Player.heros:type_name -> src.Hero
	3,  // 1: src.Player.baseModel:type_name -> src.BaseModel
	4,  // 2: src.Player.settings:type_name -> src.Player.SettingsEntry
	0,  // 3: src.Player.player_enum:type_name -> src.PlayerEnum
	0,  // 4: src.Player.enums:type_name -> src.PlayerEnum
	5,  // 5: src.Player.models:type_name -> src.Player.ModelsEntry
	3,  // 6: src.Player.skip_me:type_name -> src.BaseModel
	6,  // 7: src.Player.nested:type_name -> src.Player.NestedM
	6,  // 8: src.Player.nesteds:type_name -> src.Player.NestedM
	7,  // 9: src.Player.nested_map:type_name -> src.Player.NestedMapEntry
	9,  // 10: src.Player.nested2:type_name -> src.Player.NestedM.Nested2
	9,  // 11: src.Player.n2s:type_name -> src.Player.NestedM.Nested2
	8,  // 12: src.Player.nested2_map:type_name -> src.Player.Nested2MapEntry
	3,  // 13: src.Player.ModelsEntry.value:type_name -> src.BaseModel
	10, // 14: src.Player.NestedM.f3:type_name -> src.Player.NestedM.F3Entry
	9,  // 15: src.Player.NestedM.f4:type_name -> src.Player.NestedM.Nested2
	11, // 16: src.Player.NestedM.f5:type_name -> src.Player.NestedM.F5Entry
	9,  // 17: src.Player.NestedM.f6:type_name -> src.Player.NestedM.Nested2
	6,  // 18: src.Player.NestedMapEntry.value:type_name -> src.Player.NestedM
	9,  // 19: src.Player.Nested2MapEntry.value:type_name -> src.Player.NestedM.Nested2
	12, // 20: src.Player.NestedM.Nested2.f3:type_name -> src.Player.NestedM.Nested2.F3Entry
	9,  // 21: src.Player.NestedM.F5Entry.value:type_name -> src.Player.NestedM.Nested2
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_players_proto_init() }
func file_players_proto_init() {
	if File_players_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_players_proto_rawDesc), len(file_players_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_players_proto_goTypes,
		DependencyIndexes: file_players_proto_depIdxs,
		EnumInfos:         file_players_proto_enumTypes,
		MessageInfos:      file_players_proto_msgTypes,
	}.Build()
	File_players_proto = out.File
	file_players_proto_goTypes = nil
	file_players_proto_depIdxs = nil
}
