// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
//  protoc-gen-orm v0.1.0
//  protoc           v7.34.1
// source: players.proto
// time 2026-06-05

package src

import (
	proto "google.golang.org/protobuf/proto"
)

// GetPlayerTable 转换actor state为Player类型
func GetPlayerTable(holder interface{ GetStateValue() proto.Message }) *Player {
	return holder.GetStateValue().(*Player)
}

// SetVersion 设置Player的版本号
func (x *Player) SetVersion(ver int64) {
	if x == nil {
		return
	}
	x.Version = ver
}

// ShardingKey 供 go-orm 分片路由（orm.ShardingKeyProvider）
func (x *Player) ShardingKey() int64 {
	return x.Id
}

func SetPlayerDefaults(r *Player) {
	if r == nil {
		return
	}
	if r.Heros == nil {
		r.Heros = make([]*Hero, 0)
	}
	if r.BaseModel == nil {
		r.BaseModel = &BaseModel{}
		SetBaseModelDefaults(r.BaseModel)
	}
	if r.Settings == nil {
		r.Settings = make(map[string]int32)
	}
	if r.Array == nil {
		r.Array = make([]int32, 0)
	}
	if r.Enums == nil {
		r.Enums = make([]PlayerEnum, 0)
	}
	if r.Data == nil {
		r.Data = make([]byte, 0)
	}
	if r.Models == nil {
		r.Models = make(map[int32]*BaseModel)
	}
	if r.Nested == nil {
		r.Nested = &Player_NestedM{}
		SetPlayer_NestedMDefaults(r.Nested)
	}
	if r.Nesteds == nil {
		r.Nesteds = make([]*Player_NestedM, 0)
	}
	if r.NestedMap == nil {
		r.NestedMap = make(map[string]*Player_NestedM)
	}
	if r.Nested2 == nil {
		r.Nested2 = &Player_NestedM_Nested2{}
		SetPlayer_NestedM_Nested2Defaults(r.Nested2)
	}
	if r.N2S == nil {
		r.N2S = make([]*Player_NestedM_Nested2, 0)
	}
	if r.Nested2Map == nil {
		r.Nested2Map = make(map[string]*Player_NestedM_Nested2)
	}

}

// nested messages
func SetPlayer_NestedMDefaults(r *Player_NestedM) {
	if r == nil {
		return
	}
	if r.F3 == nil {
		r.F3 = make(map[string]int32)
	}
	if r.F4 == nil {
		r.F4 = &Player_NestedM_Nested2{}
		SetPlayer_NestedM_Nested2Defaults(r.F4)
	}
	if r.F5 == nil {
		r.F5 = make(map[string]*Player_NestedM_Nested2)
	}
	if r.F6 == nil {
		r.F6 = make([]*Player_NestedM_Nested2, 0)
	}

}

// nested messages
func SetPlayer_NestedM_Nested2Defaults(r *Player_NestedM_Nested2) {
	if r == nil {
		return
	}
	if r.F3 == nil {
		r.F3 = make(map[string]int32)
	}

}

func SetHeroDefaults(r *Hero) {
	if r == nil {
		return
	}

}

func SetBaseModelDefaults(r *BaseModel) {
	if r == nil {
		return
	}

}
