// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: tables.proto

package src

import (
	_ "github.com/wxdqing/protoc-gen-go-orm/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OuterEnum int32

const (
	OuterEnum_E1 OuterEnum = 0
	OuterEnum_E2 OuterEnum = 1
	OuterEnum_E3 OuterEnum = 2
)

// Enum value maps for OuterEnum.
var (
	OuterEnum_name = map[int32]string{
		0: "E1",
		1: "E2",
		2: "E3",
	}
	OuterEnum_value = map[string]int32{
		"E1": 0,
		"E2": 1,
		"E3": 2,
	}
)

func (x OuterEnum) Enum() *OuterEnum {
	p := new(OuterEnum)
	*p = x
	return p
}

func (x OuterEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OuterEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_tables_proto_enumTypes[0].Descriptor()
}

func (OuterEnum) Type() protoreflect.EnumType {
	return &file_tables_proto_enumTypes[0]
}

func (x OuterEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OuterEnum.Descriptor instead.
func (OuterEnum) EnumDescriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{0}
}

type SecondMessage_InnerEnum int32

const (
	SecondMessage_IE1 SecondMessage_InnerEnum = 0
	SecondMessage_IE2 SecondMessage_InnerEnum = 1
	SecondMessage_IE3 SecondMessage_InnerEnum = 2
)

// Enum value maps for SecondMessage_InnerEnum.
var (
	SecondMessage_InnerEnum_name = map[int32]string{
		0: "IE1",
		1: "IE2",
		2: "IE3",
	}
	SecondMessage_InnerEnum_value = map[string]int32{
		"IE1": 0,
		"IE2": 1,
		"IE3": 2,
	}
)

func (x SecondMessage_InnerEnum) Enum() *SecondMessage_InnerEnum {
	p := new(SecondMessage_InnerEnum)
	*p = x
	return p
}

func (x SecondMessage_InnerEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecondMessage_InnerEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_tables_proto_enumTypes[1].Descriptor()
}

func (SecondMessage_InnerEnum) Type() protoreflect.EnumType {
	return &file_tables_proto_enumTypes[1]
}

func (x SecondMessage_InnerEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecondMessage_InnerEnum.Descriptor instead.
func (SecondMessage_InnerEnum) EnumDescriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{1, 0}
}

type Example struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WithNewTags     string                 `protobuf:"bytes,1,opt,name=with_new_tags,json=withNewTags,proto3" json:"with_new_tags,omitempty"`
	WithNewMultiple string                 `protobuf:"bytes,2,opt,name=with_new_multiple,json=withNewMultiple,proto3" json:"with_new_multiple,omitempty"`
	ReplaceDefault  string                 `protobuf:"bytes,3,opt,name=replace_default,json=replaceDefault,proto3" json:"replace_default,omitempty"`
	// Types that are valid to be assigned to OneOf:
	//
	//	*Example_A
	//	*Example_BJk
	OneOf         isExample_OneOf              `protobuf_oneof:"one_of"`
	Ll            []int32                      `protobuf:"varint,7,rep,packed,name=ll,proto3" json:"ll,omitempty"`
	Mm            map[string]int32             `protobuf:"bytes,8,rep,name=mm,proto3" json:"mm,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Nn            map[int32]*EmptyFieldMessage `protobuf:"bytes,9,rep,name=nn,proto3" json:"nn,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ee            map[string]OuterEnum         `protobuf:"bytes,10,rep,name=ee,proto3" json:"ee,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=src.OuterEnum"`
	Array         []byte                       `protobuf:"bytes,11,opt,name=array,proto3" json:"array,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Example) Reset() {
	*x = Example{}
	mi := &file_tables_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example.ProtoReflect.Descriptor instead.
func (*Example) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{0}
}

func (x *Example) GetWithNewTags() string {
	if x != nil {
		return x.WithNewTags
	}
	return ""
}

func (x *Example) GetWithNewMultiple() string {
	if x != nil {
		return x.WithNewMultiple
	}
	return ""
}

func (x *Example) GetReplaceDefault() string {
	if x != nil {
		return x.ReplaceDefault
	}
	return ""
}

func (x *Example) GetOneOf() isExample_OneOf {
	if x != nil {
		return x.OneOf
	}
	return nil
}

func (x *Example) GetA() string {
	if x != nil {
		if x, ok := x.OneOf.(*Example_A); ok {
			return x.A
		}
	}
	return ""
}

func (x *Example) GetBJk() int32 {
	if x != nil {
		if x, ok := x.OneOf.(*Example_BJk); ok {
			return x.BJk
		}
	}
	return 0
}

func (x *Example) GetLl() []int32 {
	if x != nil {
		return x.Ll
	}
	return nil
}

func (x *Example) GetMm() map[string]int32 {
	if x != nil {
		return x.Mm
	}
	return nil
}

func (x *Example) GetNn() map[int32]*EmptyFieldMessage {
	if x != nil {
		return x.Nn
	}
	return nil
}

func (x *Example) GetEe() map[string]OuterEnum {
	if x != nil {
		return x.Ee
	}
	return nil
}

func (x *Example) GetArray() []byte {
	if x != nil {
		return x.Array
	}
	return nil
}

type isExample_OneOf interface {
	isExample_OneOf()
}

type Example_A struct {
	A string `protobuf:"bytes,5,opt,name=a,proto3,oneof"`
}

type Example_BJk struct {
	BJk int32 `protobuf:"varint,6,opt,name=b_jk,json=bJk,proto3,oneof"`
}

func (*Example_A) isExample_OneOf() {}

func (*Example_BJk) isExample_OneOf() {}

type SecondMessage struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	WithNewTags     string                  `protobuf:"bytes,1,opt,name=with_new_tags,json=withNewTags,proto3" json:"with_new_tags,omitempty"`
	WithNewMultiple string                  `protobuf:"bytes,2,opt,name=with_new_multiple,json=withNewMultiple,proto3" json:"with_new_multiple,omitempty"`
	ReplaceDefault  string                  `protobuf:"bytes,3,opt,name=replace_default,json=replaceDefault,proto3" json:"replace_default,omitempty"`
	InnerEnum       SecondMessage_InnerEnum `protobuf:"varint,4,opt,name=inner_enum,json=innerEnum,proto3,enum=src.SecondMessage_InnerEnum" json:"inner_enum,omitempty"`
	OuterEnum       OuterEnum               `protobuf:"varint,5,opt,name=outer_enum,json=outerEnum,proto3,enum=src.OuterEnum" json:"outer_enum,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SecondMessage) Reset() {
	*x = SecondMessage{}
	mi := &file_tables_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecondMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecondMessage) ProtoMessage() {}

func (x *SecondMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecondMessage.ProtoReflect.Descriptor instead.
func (*SecondMessage) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{1}
}

func (x *SecondMessage) GetWithNewTags() string {
	if x != nil {
		return x.WithNewTags
	}
	return ""
}

func (x *SecondMessage) GetWithNewMultiple() string {
	if x != nil {
		return x.WithNewMultiple
	}
	return ""
}

func (x *SecondMessage) GetReplaceDefault() string {
	if x != nil {
		return x.ReplaceDefault
	}
	return ""
}

func (x *SecondMessage) GetInnerEnum() SecondMessage_InnerEnum {
	if x != nil {
		return x.InnerEnum
	}
	return SecondMessage_IE1
}

func (x *SecondMessage) GetOuterEnum() OuterEnum {
	if x != nil {
		return x.OuterEnum
	}
	return OuterEnum_E1
}

type ThirdExample struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	InnerExample  *ThirdExample_InnerExample `protobuf:"bytes,1,opt,name=inner_example,json=innerExample,proto3" json:"inner_example,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdExample) Reset() {
	*x = ThirdExample{}
	mi := &file_tables_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdExample) ProtoMessage() {}

func (x *ThirdExample) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdExample.ProtoReflect.Descriptor instead.
func (*ThirdExample) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{2}
}

func (x *ThirdExample) GetInnerExample() *ThirdExample_InnerExample {
	if x != nil {
		return x.InnerExample
	}
	return nil
}

type EmptyFieldMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyFieldMessage) Reset() {
	*x = EmptyFieldMessage{}
	mi := &file_tables_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyFieldMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyFieldMessage) ProtoMessage() {}

func (x *EmptyFieldMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyFieldMessage.ProtoReflect.Descriptor instead.
func (*EmptyFieldMessage) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{3}
}

type ThirdExample_InnerExample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Yes           int32                  `protobuf:"varint,2,opt,name=yes,proto3" json:"yes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdExample_InnerExample) Reset() {
	*x = ThirdExample_InnerExample{}
	mi := &file_tables_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdExample_InnerExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdExample_InnerExample) ProtoMessage() {}

func (x *ThirdExample_InnerExample) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdExample_InnerExample.ProtoReflect.Descriptor instead.
func (*ThirdExample_InnerExample) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ThirdExample_InnerExample) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ThirdExample_InnerExample) GetYes() int32 {
	if x != nil {
		return x.Yes
	}
	return 0
}

var File_tables_proto protoreflect.FileDescriptor

const file_tables_proto_rawDesc = "" +
	"\n" +
	"\ftables.proto\x12\x03src\x1a\x10orm.option.proto\"\x9c\x06\n" +
	"\aExample\x12G\n" +
	"\rwith_new_tags\x18\x01 \x01(\tB#\x9a\x84\x9e\x03\x1egraphql:\"withNewTags,optional\"R\vwithNewTags\x12e\n" +
	"\x11with_new_multiple\x18\x02 \x01(\tB9\x9a\x84\x9e\x034graphql:\"withNewTags,optional\" xml:\"multi,omitempty\"R\x0fwithNewMultiple\x12D\n" +
	"\x0freplace_default\x18\x03 \x01(\tB\x1b\x9a\x84\x9e\x03\x16json:\"replacePrevious\"R\x0ereplaceDefault\x12\x1d\n" +
	"\x01a\x18\x05 \x01(\tB\r\x9a\x84\x9e\x03\bjson:\"A\"H\x00R\x01a\x12%\n" +
	"\x04b_jk\x18\x06 \x01(\x05B\x10\x9a\x84\x9e\x03\vjson:\"b_Jk\"H\x00R\x03bJk\x12\x0e\n" +
	"\x02ll\x18\a \x03(\x05R\x02ll\x124\n" +
	"\x02mm\x18\b \x03(\v2\x14.src.Example.MmEntryB\x0e\x9a\x84\x9e\x03\tjson:\"mm\"R\x02mm\x124\n" +
	"\x02nn\x18\t \x03(\v2\x14.src.Example.NnEntryB\x0e\x9a\x84\x9e\x03\tjson:\"nn\"R\x02nn\x124\n" +
	"\x02ee\x18\n" +
	" \x03(\v2\x14.src.Example.EeEntryB\x0e\x9a\x84\x9e\x03\tjson:\"ee\"R\x02ee\x12'\n" +
	"\x05array\x18\v \x01(\fB\x11\x9a\x84\x9e\x03\fjson:\"array\"R\x05array\x1a5\n" +
	"\aMmEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aM\n" +
	"\aNnEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.src.EmptyFieldMessageR\x05value:\x028\x01\x1aE\n" +
	"\aEeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\x0e2\x0e.src.OuterEnumR\x05value:\x028\x01B-\n" +
	"\x06one_of\x12#\x9a\x84\x9e\x03\x1egraphql:\"withNewTags,optional\"\"\xc7\x03\n" +
	"\rSecondMessage\x12G\n" +
	"\rwith_new_tags\x18\x01 \x01(\tB#\x9a\x84\x9e\x03\x1egraphql:\"withNewTags,optional\"R\vwithNewTags\x12e\n" +
	"\x11with_new_multiple\x18\x02 \x01(\tB9\x9a\x84\x9e\x034graphql:\"withNewTags,optional\" xml:\"multi,omitempty\"R\x0fwithNewMultiple\x12D\n" +
	"\x0freplace_default\x18\x03 \x01(\tB\x1b\x9a\x84\x9e\x03\x16json:\"replacePrevious\"R\x0ereplaceDefault\x12R\n" +
	"\n" +
	"inner_enum\x18\x04 \x01(\x0e2\x1c.src.SecondMessage.InnerEnumB\x15\x9a\x84\x9e\x03\x10json:\"innerEnum\"R\tinnerEnum\x12D\n" +
	"\n" +
	"outer_enum\x18\x05 \x01(\x0e2\x0e.src.OuterEnumB\x15\x9a\x84\x9e\x03\x10json:\"outerEnum\"R\touterEnum\"&\n" +
	"\tInnerEnum\x12\a\n" +
	"\x03IE1\x10\x00\x12\a\n" +
	"\x03IE2\x10\x01\x12\a\n" +
	"\x03IE3\x10\x02\"\xb9\x01\n" +
	"\fThirdExample\x12V\n" +
	"\rinner_example\x18\x01 \x01(\v2\x1e.src.ThirdExample.InnerExampleB\x11\x9a\x84\x9e\x03\fjson:\"inner\"R\finnerExample\x1aQ\n" +
	"\fInnerExample\x12\x1f\n" +
	"\x02id\x18\x01 \x01(\tB\x0f\x9a\x84\x9e\x03\n" +
	"json:\"yes\"R\x02id\x12 \n" +
	"\x03yes\x18\x02 \x01(\x05B\x0e\x9a\x84\x9e\x03\tjson:\"id\"R\x03yes\"\x13\n" +
	"\x11EmptyFieldMessage*#\n" +
	"\tOuterEnum\x12\x06\n" +
	"\x02E1\x10\x00\x12\x06\n" +
	"\x02E2\x10\x01\x12\x06\n" +
	"\x02E3\x10\x02B3Z1github.com/wxdqing/protoc-gen-go-orm/examples/srcb\x06proto3"

var (
	file_tables_proto_rawDescOnce sync.Once
	file_tables_proto_rawDescData []byte
)

func file_tables_proto_rawDescGZIP() []byte {
	file_tables_proto_rawDescOnce.Do(func() {
		file_tables_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tables_proto_rawDesc), len(file_tables_proto_rawDesc)))
	})
	return file_tables_proto_rawDescData
}

var file_tables_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tables_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_tables_proto_goTypes = []any{
	(OuterEnum)(0),                    // 0: src.OuterEnum
	(SecondMessage_InnerEnum)(0),      // 1: src.SecondMessage.InnerEnum
	(*Example)(nil),                   // 2: src.Example
	(*SecondMessage)(nil),             // 3: src.SecondMessage
	(*ThirdExample)(nil),              // 4: src.ThirdExample
	(*EmptyFieldMessage)(nil),         // 5: src.EmptyFieldMessage
	nil,                               // 6: src.Example.MmEntry
	nil,                               // 7: src.Example.NnEntry
	nil,                               // 8: src.Example.EeEntry
	(*ThirdExample_InnerExample)(nil), // 9: src.ThirdExample.InnerExample
}
var file_tables_proto_depIdxs = []int32{
	6, // 0: src.Example.mm:type_name -> src.Example.MmEntry
	7, // 1: src.Example.nn:type_name -> src.Example.NnEntry
	8, // 2: src.Example.ee:type_name -> src.Example.EeEntry
	1, // 3: src.SecondMessage.inner_enum:type_name -> src.SecondMessage.InnerEnum
	0, // 4: src.SecondMessage.outer_enum:type_name -> src.OuterEnum
	9, // 5: src.ThirdExample.inner_example:type_name -> src.ThirdExample.InnerExample
	5, // 6: src.Example.NnEntry.value:type_name -> src.EmptyFieldMessage
	0, // 7: src.Example.EeEntry.value:type_name -> src.OuterEnum
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_tables_proto_init() }
func file_tables_proto_init() {
	if File_tables_proto != nil {
		return
	}
	file_tables_proto_msgTypes[0].OneofWrappers = []any{
		(*Example_A)(nil),
		(*Example_BJk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tables_proto_rawDesc), len(file_tables_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tables_proto_goTypes,
		DependencyIndexes: file_tables_proto_depIdxs,
		EnumInfos:         file_tables_proto_enumTypes,
		MessageInfos:      file_tables_proto_msgTypes,
	}.Build()
	File_tables_proto = out.File
	file_tables_proto_goTypes = nil
	file_tables_proto_depIdxs = nil
}
