// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
//  protoc-gen-orm v0.1.0
//  protoc           v7.34.1
// source: tables.proto
// time 2026-06-05

package src

func SetExampleDefaults(r *Example) {
	if r == nil {
		return
	}
	if r.Ll == nil {
		r.Ll = make([]int32, 0)
	}
	if r.Mm == nil {
		r.Mm = make(map[string]int32)
	}
	if r.Nn == nil {
		r.Nn = make(map[int32]*EmptyFieldMessage)
	}
	if r.Ee == nil {
		r.Ee = make(map[string]OuterEnum)
	}
	if r.Array == nil {
		r.Array = make([]byte, 0)
	}

}

func SetSecondMessageDefaults(r *SecondMessage) {
	if r == nil {
		return
	}

}

func SetThirdExampleDefaults(r *ThirdExample) {
	if r == nil {
		return
	}
	if r.InnerExample == nil {
		r.InnerExample = &ThirdExample_InnerExample{}
		SetThirdExample_InnerExampleDefaults(r.InnerExample)
	}

}

// nested messages
func SetThirdExample_InnerExampleDefaults(r *ThirdExample_InnerExample) {
	if r == nil {
		return
	}

}

func SetEmptyFieldMessageDefaults(r *EmptyFieldMessage) {
	if r == nil {
		return
	}

}
