// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
//  protoc-gen-orm v0.1.0
//  protoc           v7.34.1
// dbType           tcaplus
// source: players.proto
// time 2026-06-04

package tcaplus

import (
	proto "google.golang.org/protobuf/proto"
	reflect "reflect"
)

import "github.com/wxdqing/protoc-gen-go-orm/examples/src"

// methods for src.Player in tcaplus

func (m *Player) TableName() string {
	return "player" //string(m.ProtoReflect().Descriptor().Name())
}

func (m *Player) NewValue() proto.Message {
	return &src.Player{}
}

func (m *Player) PrimaryKey() []any {
	return []any{m.Id}
}

func (m *Player) PrimaryKeyNames() []string {
	return []string{
		"id",
	}
}

func (m *Player) ToPrimaryKeyMap() map[string]any {
	ret := make(map[string]any)

	if !m.isZeroValue(m.Id) {
		ret["id"] = m.Id
	}

	return ret
}

func (m *Player) ToPrimaryKeyStruct() any {
	s := &Player{}

	if !m.isZeroValue(m.Id) {
		s.Id = m.Id
	}

	return s
}

func (m *Player) Indexes() []any {
	return []any{m.Name}
}

func (m *Player) IndexNames() []string {
	return []string{"name"}
}

func (m *Player) ToIndexMap() map[string]any {
	ret := map[string]any{}

	if !m.isZeroValue(m.Name) {
		ret["name"] = m.Name
	}

	return ret
}

func (m *Player) ToIndexStruct() any {
	s := &Player{}

	if !m.isZeroValue(m.Name) {
		s.Name = m.Name
	}

	return s
}

func (m *Player) isZeroValue(val any) bool {
	rv := reflect.ValueOf(val)
	return rv.IsZero() //|| rv.IsNil()
}

func (m *Player) EncodeFrom(value proto.Message) error {
	return m.EncodeFromContext(nil, value)
}

func (m *Player) EncodeFromContext(ctx Context, value proto.Message) error {
	if hook, ok := any(m).(BeforeEncodeHook); ok {
		if err := hook.BeforeEncode(ctx, value); err != nil {
			return err
		}
	}
	r := value.(*src.Player)
	m.Id = r.Id // set pk

	m.Name = r.Name // set index

	d, err := proto.Marshal(value)
	if err != nil {
		return err
	}
	m.Data = d
	vp := value.(interface {
		GetVersion() int64
	})
	m.Version = vp.GetVersion()
	if hook, ok := any(m).(AfterEncodeHook); ok {
		if err := hook.AfterEncode(ctx, value); err != nil {
			return err
		}
	}
	return nil
}

func (m *Player) DecodeTo(value proto.Message) error {
	return m.DecodeToContext(nil, value)
}

func (m *Player) DecodeToContext(ctx Context, value proto.Message) error {
	if hook, ok := any(m).(BeforeDecodeHook); ok {
		if err := hook.BeforeDecode(ctx, value); err != nil {
			return err
		}
	}
	err := proto.Unmarshal(m.Data, value)
	if err != nil {
		return err
	}
	vp := value.(interface {
		SetVersion(ver int64)
	})
	vp.SetVersion(m.Version)
	src.SetPlayerDefaults(value.(*src.Player))
	if hook, ok := any(m).(AfterDecodeHook); ok {
		if err := hook.AfterDecode(ctx, value); err != nil {
			return err
		}
	}
	return nil
}

// SetVersion 设置Player的版本号
func (m *Player) SetVersion(ver int64) {
	if m == nil {
		return
	}
	m.Version = ver
}
