// Code generated by protoc-gen-go-orm. DO NOT EDIT.
// versions:
//  protoc-gen-go-orm v0.1.0
//  protoc           v7.34.1
// source: integration_game.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: tca_integration_game.proto

package tcaplus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tcaplus表结构定义
type GameRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      int64                  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version       int64                  `protobuf:"varint,11,opt,name=version,proto3" json:"version,omitempty"`
	Data          []byte                 `protobuf:"bytes,999,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,1000,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,1001,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRole) Reset() {
	*x = GameRole{}
	mi := &file_tca_integration_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRole) ProtoMessage() {}

func (x *GameRole) ProtoReflect() protoreflect.Message {
	mi := &file_tca_integration_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRole.ProtoReflect.Descriptor instead.
func (*GameRole) Descriptor() ([]byte, []int) {
	return file_tca_integration_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameRole) GetServerId() int64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *GameRole) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *GameRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameRole) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GameRole) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GameRole) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GameRole) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_tca_integration_game_proto protoreflect.FileDescriptor

const file_tca_integration_game_proto_rawDesc = "" +
	"\n" +
	"\x1atca_integration_game.proto\x12\atcaplus\x1a\x1dtcaplusservice.optionv1.proto\"\xeb\x02\n" +
	"\bGameRole\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x03R\bserverId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x03R\x06roleId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\v \x01(\x03R\aversion\x12\x13\n" +
	"\x04data\x18\xe7\a \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"created_at\x18\xe8\a \x01(\x03R\tcreatedAt\x12\x1e\n" +
	"\n" +
	"updated_at\x18\xe9\a \x01(\x03R\tupdatedAt:\xa5\x01\x82\xa6\x1d\x12server_id, role_id\x8a\xa6\x1d)idx_game_role_server_name(server_id,name)\x8a\xa6\x1d+idx_game_role_server_level(server_id,level)\x8a\xa6\x1d\"idx_game_role_name(server_id,name)\xaa\xa6\x1d\tserver_idB\x16Z\x14src/internal/tcaplusb\x06proto3"

var (
	file_tca_integration_game_proto_rawDescOnce sync.Once
	file_tca_integration_game_proto_rawDescData []byte
)

func file_tca_integration_game_proto_rawDescGZIP() []byte {
	file_tca_integration_game_proto_rawDescOnce.Do(func() {
		file_tca_integration_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tca_integration_game_proto_rawDesc), len(file_tca_integration_game_proto_rawDesc)))
	})
	return file_tca_integration_game_proto_rawDescData
}

var file_tca_integration_game_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tca_integration_game_proto_goTypes = []any{
	(*GameRole)(nil), // 0: tcaplus.GameRole
}
var file_tca_integration_game_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tca_integration_game_proto_init() }
func file_tca_integration_game_proto_init() {
	if File_tca_integration_game_proto != nil {
		return
	}
	file_tcaplusservice_optionv1_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tca_integration_game_proto_rawDesc), len(file_tca_integration_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tca_integration_game_proto_goTypes,
		DependencyIndexes: file_tca_integration_game_proto_depIdxs,
		MessageInfos:      file_tca_integration_game_proto_msgTypes,
	}.Build()
	File_tca_integration_game_proto = out.File
	file_tca_integration_game_proto_goTypes = nil
	file_tca_integration_game_proto_depIdxs = nil
}
