// TcaplusService option Ver.1
// Author: Tcaplus
// 2016-8-1
// Modified: 2018-02-12 Add Crypto options

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: tcaplusservice.optionv1.proto

package tcaplus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_tcaplusservice_optionv1_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         60000,
		Name:          "tcaplusservice.tcaplus_primary_key",
		Tag:           "bytes,60000,opt,name=tcaplus_primary_key",
		Filename:      "tcaplusservice.optionv1.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         60001,
		Name:          "tcaplusservice.tcaplus_index",
		Tag:           "bytes,60001,rep,name=tcaplus_index",
		Filename:      "tcaplusservice.optionv1.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         60002,
		Name:          "tcaplusservice.tcaplus_field_cipher_suite",
		Tag:           "bytes,60002,opt,name=tcaplus_field_cipher_suite",
		Filename:      "tcaplusservice.optionv1.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         60003,
		Name:          "tcaplusservice.tcaplus_record_cipher_suite",
		Tag:           "bytes,60003,opt,name=tcaplus_record_cipher_suite",
		Filename:      "tcaplusservice.optionv1.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         60004,
		Name:          "tcaplusservice.tcaplus_cipher_md5",
		Tag:           "bytes,60004,opt,name=tcaplus_cipher_md5",
		Filename:      "tcaplusservice.optionv1.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         60005,
		Name:          "tcaplusservice.tcaplus_sharding_key",
		Tag:           "bytes,60005,opt,name=tcaplus_sharding_key",
		Filename:      "tcaplusservice.optionv1.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         60006,
		Name:          "tcaplusservice.tcaplus_customattr",
		Tag:           "bytes,60006,opt,name=tcaplus_customattr",
		Filename:      "tcaplusservice.optionv1.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         60000,
		Name:          "tcaplusservice.tcaplus_size",
		Tag:           "varint,60000,opt,name=tcaplus_size",
		Filename:      "tcaplusservice.optionv1.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         60001,
		Name:          "tcaplusservice.tcaplus_desc",
		Tag:           "bytes,60001,opt,name=tcaplus_desc",
		Filename:      "tcaplusservice.optionv1.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         60002,
		Name:          "tcaplusservice.tcaplus_crypto",
		Tag:           "varint,60002,opt,name=tcaplus_crypto",
		Filename:      "tcaplusservice.optionv1.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional string tcaplus_primary_key = 60000;
	E_TcaplusPrimaryKey = &file_tcaplusservice_optionv1_proto_extTypes[0] //Tcaplus Primary Key
	// repeated string tcaplus_index = 60001;
	E_TcaplusIndex = &file_tcaplusservice_optionv1_proto_extTypes[1] //Tcaplus Index
	// optional string tcaplus_field_cipher_suite = 60002;
	E_TcaplusFieldCipherSuite = &file_tcaplusservice_optionv1_proto_extTypes[2] //Tcaplus field crypto suite name
	// optional string tcaplus_record_cipher_suite = 60003;
	E_TcaplusRecordCipherSuite = &file_tcaplusservice_optionv1_proto_extTypes[3] //Tcaplus record crypto suite name
	// optional string tcaplus_cipher_md5 = 60004;
	E_TcaplusCipherMd5 = &file_tcaplusservice_optionv1_proto_extTypes[4] //Tcaplus crypto key md5
	// optional string tcaplus_sharding_key = 60005;
	E_TcaplusShardingKey = &file_tcaplusservice_optionv1_proto_extTypes[5] //Tcaplus sharding key
	// optional string tcaplus_customattr = 60006;
	E_TcaplusCustomattr = &file_tcaplusservice_optionv1_proto_extTypes[6] //Tcaplus custom define attribute
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional uint32 tcaplus_size = 60000;
	E_TcaplusSize = &file_tcaplusservice_optionv1_proto_extTypes[7] // Tcaplus field size
	// optional string tcaplus_desc = 60001;
	E_TcaplusDesc = &file_tcaplusservice_optionv1_proto_extTypes[8] // Tcaplus description
	// optional bool tcaplus_crypto = 60002;
	E_TcaplusCrypto = &file_tcaplusservice_optionv1_proto_extTypes[9] // Tcaplus crypto
)

var File_tcaplusservice_optionv1_proto protoreflect.FileDescriptor

const file_tcaplusservice_optionv1_proto_rawDesc = "" +
	"\n" +
	"\x1dtcaplusservice.optionv1.proto\x12\x0etcaplusservice\x1a google/protobuf/descriptor.proto:Q\n" +
	"\x13tcaplus_primary_key\x12\x1f.google.protobuf.MessageOptions\x18\xe0\xd4\x03 \x01(\tR\x11tcaplusPrimaryKey:F\n" +
	"\rtcaplus_index\x12\x1f.google.protobuf.MessageOptions\x18\xe1\xd4\x03 \x03(\tR\ftcaplusIndex:^\n" +
	"\x1atcaplus_field_cipher_suite\x12\x1f.google.protobuf.MessageOptions\x18\xe2\xd4\x03 \x01(\tR\x17tcaplusFieldCipherSuite:`\n" +
	"\x1btcaplus_record_cipher_suite\x12\x1f.google.protobuf.MessageOptions\x18\xe3\xd4\x03 \x01(\tR\x18tcaplusRecordCipherSuite:O\n" +
	"\x12tcaplus_cipher_md5\x12\x1f.google.protobuf.MessageOptions\x18\xe4\xd4\x03 \x01(\tR\x10tcaplusCipherMd5:S\n" +
	"\x14tcaplus_sharding_key\x12\x1f.google.protobuf.MessageOptions\x18\xe5\xd4\x03 \x01(\tR\x12tcaplusShardingKey:P\n" +
	"\x12tcaplus_customattr\x12\x1f.google.protobuf.MessageOptions\x18\xe6\xd4\x03 \x01(\tR\x11tcaplusCustomattr:B\n" +
	"\ftcaplus_size\x12\x1d.google.protobuf.FieldOptions\x18\xe0\xd4\x03 \x01(\rR\vtcaplusSize:B\n" +
	"\ftcaplus_desc\x12\x1d.google.protobuf.FieldOptions\x18\xe1\xd4\x03 \x01(\tR\vtcaplusDesc:F\n" +
	"\x0etcaplus_crypto\x12\x1d.google.protobuf.FieldOptions\x18\xe2\xd4\x03 \x01(\bR\rtcaplusCryptoB\x16Z\x14src/internal/tcaplus"

var file_tcaplusservice_optionv1_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 1: google.protobuf.FieldOptions
}
var file_tcaplusservice_optionv1_proto_depIdxs = []int32{
	0,  // 0: tcaplusservice.tcaplus_primary_key:extendee -> google.protobuf.MessageOptions
	0,  // 1: tcaplusservice.tcaplus_index:extendee -> google.protobuf.MessageOptions
	0,  // 2: tcaplusservice.tcaplus_field_cipher_suite:extendee -> google.protobuf.MessageOptions
	0,  // 3: tcaplusservice.tcaplus_record_cipher_suite:extendee -> google.protobuf.MessageOptions
	0,  // 4: tcaplusservice.tcaplus_cipher_md5:extendee -> google.protobuf.MessageOptions
	0,  // 5: tcaplusservice.tcaplus_sharding_key:extendee -> google.protobuf.MessageOptions
	0,  // 6: tcaplusservice.tcaplus_customattr:extendee -> google.protobuf.MessageOptions
	1,  // 7: tcaplusservice.tcaplus_size:extendee -> google.protobuf.FieldOptions
	1,  // 8: tcaplusservice.tcaplus_desc:extendee -> google.protobuf.FieldOptions
	1,  // 9: tcaplusservice.tcaplus_crypto:extendee -> google.protobuf.FieldOptions
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	0,  // [0:10] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_tcaplusservice_optionv1_proto_init() }
func file_tcaplusservice_optionv1_proto_init() {
	if File_tcaplusservice_optionv1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tcaplusservice_optionv1_proto_rawDesc), len(file_tcaplusservice_optionv1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 10,
			NumServices:   0,
		},
		GoTypes:           file_tcaplusservice_optionv1_proto_goTypes,
		DependencyIndexes: file_tcaplusservice_optionv1_proto_depIdxs,
		ExtensionInfos:    file_tcaplusservice_optionv1_proto_extTypes,
	}.Build()
	File_tcaplusservice_optionv1_proto = out.File
	file_tcaplusservice_optionv1_proto_goTypes = nil
	file_tcaplusservice_optionv1_proto_depIdxs = nil
}
