// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
//  protoc-gen-orm v0.1.0
//  protoc           v7.34.1
// source: list.proto
// time 2026-06-04

package metadata

import (
	mysql "github.com/wxdqing/protoc-gen-go-orm.git/examples/src/internal/mysql"
	pgsql "github.com/wxdqing/protoc-gen-go-orm.git/examples/src/internal/pgsql"
	tcaplus "github.com/wxdqing/protoc-gen-go-orm.git/examples/src/internal/tcaplus"
	proto "google.golang.org/protobuf/proto"
)

var Tables = make(map[string][]proto.Message)
var NodeTables = make(map[string]map[string][]proto.Message)

func init() { // mysql database tables
	Tables["mysql"] = []proto.Message{
		&mysql.Lister{},
		&mysql.Player{},
	}
	NodeTables["mysql"] = make(map[string][]proto.Message)
	NodeTables["mysql"]["social"] = append(NodeTables["mysql"]["social"], &mysql.Lister{})
	NodeTables["mysql"]["game"] = append(NodeTables["mysql"]["game"], &mysql.Player{}) // tcaplus database tables
	Tables["tcaplus"] = []proto.Message{
		&tcaplus.Lister{},
		&tcaplus.Player{},
	}
	NodeTables["tcaplus"] = make(map[string][]proto.Message)
	NodeTables["tcaplus"]["social"] = append(NodeTables["tcaplus"]["social"], &tcaplus.Lister{})
	NodeTables["tcaplus"]["game"] = append(NodeTables["tcaplus"]["game"], &tcaplus.Player{}) // pgsql database tables
	Tables["pgsql"] = []proto.Message{
		&pgsql.Lister{},
		&pgsql.Player{},
	}
	NodeTables["pgsql"] = make(map[string][]proto.Message)
	NodeTables["pgsql"]["social"] = append(NodeTables["pgsql"]["social"], &pgsql.Lister{})
	NodeTables["pgsql"]["game"] = append(NodeTables["pgsql"]["game"], &pgsql.Player{})
}

func GetAllTables(dbType string) []proto.Message {
	if m, ok := Tables[dbType]; ok {
		return m
	}
	return nil
}

func GetNodeTables(dbType string, nodeType string) []proto.Message {
	if m, ok := NodeTables[dbType]; ok {
		return m[nodeType]
	}
	return nil
}
