// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
//  protoc-gen-orm v0.1.0
//  protoc           v7.34.1
// dbType           redis
// source: list.proto
// time 2026-06-04

package redis

import (
	proto "google.golang.org/protobuf/proto"
	reflect "reflect"
)

import "github.com/wxdqing/protoc-gen-go-orm/examples/src"

// methods for src.Lister in redis

func (m *Lister) TableName() string {
	return "lister" //string(m.ProtoReflect().Descriptor().Name())
}

func (m *Lister) NewValue() proto.Message {
	return &src.Lister{}
}

func (m *Lister) PrimaryKey() []any {
	return []any{m.Rid, m.Id}
}

func (m *Lister) PrimaryKeyNames() []string {
	return []string{
		"rid", "id",
	}
}

func (m *Lister) ToPrimaryKeyMap() map[string]any {
	ret := make(map[string]any)

	if !m.isZeroValue(m.Rid) {
		ret["rid"] = m.Rid
	}
	if !m.isZeroValue(m.Id) {
		ret["id"] = m.Id
	}

	return ret
}

func (m *Lister) ToPrimaryKeyStruct() any {
	s := &Lister{}

	if !m.isZeroValue(m.Rid) {
		s.Rid = m.Rid
	}
	if !m.isZeroValue(m.Id) {
		s.Id = m.Id
	}

	return s
}

func (m *Lister) Indexes() []any {
	return []any{m.Rid}
}

func (m *Lister) IndexNames() []string {
	return []string{"rid"}
}

func (m *Lister) ToIndexMap() map[string]any {
	ret := map[string]any{}

	if !m.isZeroValue(m.Rid) {
		ret["rid"] = m.Rid
	}

	return ret
}

func (m *Lister) ToIndexStruct() any {
	s := &Lister{}

	if !m.isZeroValue(m.Rid) {
		s.Rid = m.Rid
	}

	return s
}

func (m *Lister) isZeroValue(val any) bool {
	rv := reflect.ValueOf(val)
	return rv.IsZero() //|| rv.IsNil()
}

func (m *Lister) EncodeFrom(value proto.Message) error {
	return m.EncodeFromContext(nil, value)
}

func (m *Lister) EncodeFromContext(ctx Context, value proto.Message) error {
	if hook, ok := any(m).(BeforeEncodeHook); ok {
		if err := hook.BeforeEncode(ctx, value); err != nil {
			return err
		}
	}
	r := value.(*src.Lister)
	m.Rid = r.Rid // set pk
	m.Rid = r.Rid // set index
	m.Id = r.Id   // set pk

	d, err := proto.Marshal(value)
	if err != nil {
		return err
	}
	m.Data = d

	if hook, ok := any(m).(AfterEncodeHook); ok {
		if err := hook.AfterEncode(ctx, value); err != nil {
			return err
		}
	}
	return nil
}

func (m *Lister) DecodeTo(value proto.Message) error {
	return m.DecodeToContext(nil, value)
}

func (m *Lister) DecodeToContext(ctx Context, value proto.Message) error {
	if hook, ok := any(m).(BeforeDecodeHook); ok {
		if err := hook.BeforeDecode(ctx, value); err != nil {
			return err
		}
	}
	err := proto.Unmarshal(m.Data, value)
	if err != nil {
		return err
	}

	src.SetListerDefaults(value.(*src.Lister))
	if hook, ok := any(m).(AfterDecodeHook); ok {
		if err := hook.AfterDecode(ctx, value); err != nil {
			return err
		}
	}
	return nil
}
