// Code generated by protoc-gen-go-orm. DO NOT EDIT.
// versions:
//  protoc-gen-go-orm v0.1.0
//  protoc           v7.34.1
// source: tables.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rd_tables.proto

package redis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rd_tables_proto protoreflect.FileDescriptor

const file_rd_tables_proto_rawDesc = "" +
	"\n" +
	"\x0frd_tables.proto\x12\x05redisBBZ@github.com/wxdqing/protoc-gen-go-orm/examples/src/internal/redisb\x06proto3"

var file_rd_tables_proto_goTypes = []any{}
var file_rd_tables_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rd_tables_proto_init() }
func file_rd_tables_proto_init() {
	if File_rd_tables_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rd_tables_proto_rawDesc), len(file_rd_tables_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rd_tables_proto_goTypes,
		DependencyIndexes: file_rd_tables_proto_depIdxs,
	}.Build()
	File_rd_tables_proto = out.File
	file_rd_tables_proto_goTypes = nil
	file_rd_tables_proto_depIdxs = nil
}
